#!/bin/sh

rm config.cache config.status -f

CC=m68k-elf-gcc \
CFLAGS="-Os -D__uClinux__ -I/opt/uClinux/uClinux-dist/lib/uClibc/include -I/opt/uClinux/uClinux-dist/linux-2.4.x/include -m5307 -Wa,-S -Wa,-m5307 -msep-data " \
LDFLAGS="-Wl,-elf2flt -Wl,-move-rodata -L/opt/uClinux/uClinux-dist/lib/uClibc/lib -lc" \
./configure --prefix=/opt/uClinux/uClinux-dist/minigui/m68k-elf/ \
    --build=i386-linux \
    --host=m68k-elf-linux \
    --target=m68k-elf-linux \
    --disable-shared \
    --disable-lite \
    --disable-standalone \
    --enable-incoreres \
    --enable-flatstyle \
    --disable-newgal \
    --disable-micemoveable \
    --disable-cursor \
    --enable-fblin1l \
    --enable-fblin1r \
    --disable-fblin8 \
    --disable-fblin16 \
    --disable-fblin32 \
    --disable-textmode \
    --enable-dummyial \
    --disable-mc68x328ial \
    --disable-nativeial \
    --disable-qvfbial \
    --disable-qpfsupport \
    --disable-ttfsupport \
    --disable-type1support \
    --disable-latin9support \
    --disable-gbksupport \
    --disable-big5support \
    --disable-unicodesupport \
    --disable-savebitmap \
    --disable-jpgsupport \
    --disable-pngsupport \
    --disable-imegb2312 \
    --disable-imegb2312py \
    --disable-aboutdlg \
    --disable-savescreen \
    --enable-grayscreen \
    --enable-tinyscreen
