#!/bin/sh

#
# Please make sure that the following things are OK:
#
#   1. You have installed the GNU arm-elf-tools already.
#   2. Your eCos for iPAQ has been installed into the directory of '/tmp/ipaq_ecos/install'.
#   3. You have set ECOS_RESPOSITORY and PATH correctly.
#

rm config.cache config.status -f

CC=arm-elf-gcc \
CFLAGS="-I/tmp/ipaq_ecos/install/include  -D__ECOS -D__NOLINUX__ -DUNIX=1 -mcpu=strongarm -Wall -O2 -g" \
LDFLAGS="-nostdlib" \
./configure --prefix=/tmp/ipaq_ecos/install/ \
    --build=i386-linux \
    --host=arm-elf-linux \
    --target=arm-elf-linux \
    --disable-shared \
    --disable-lite \
    --disable-standalone \
    --enable-incoreres \
    --enable-flatstyle \
    --enable-newgal \
    --disable-videofbcon \
    --disable-videoqvfb \
    --enable-videodummy \
    --enable-videoecoslcd \
    --disable-nativegal \
    --disable-nativegalqvfb \
    --disable-micemoveable \
    --disable-cursor \
    --disable-fblin1l \
    --disable-fblin16 \
    --disable-fblin32 \
    --disable-textmode \
    --enable-ipaqial \
    --enable-dummyial \
    --disable-nativeial \
    --disable-qvfbial \
    --disable-qpfsupport \
    --disable-ttfsupport \
    --disable-type1support \
    --disable-latin9support \
    --disable-gbksupport \
    --disable-big5support \
    --disable-unicodesupport \
    --disable-savebitmap \
    --disable-jpgsupport \
    --disable-pngsupport \
    --disable-imegb2312 \
    --disable-imegb2312py \
    --disable-aboutdlg \
    --disable-savescreen \
    --enable-grayscreen \
    --enable-tinyscreen \
    --disable-libvcongui

