#!/bin/bash

rm config.cache config.status -f

function config 
{
CC=armv4l-unknown-linux-gcc \
./configure --prefix=/opt/host/armv4l/armv4l-unknown-linux \
    --build=i386-linux \
    --host=arm-unknown-linux \
    --target=arm-unknown-linux \
    --disable-debug \
    --disable-static \
    --disable-lite \
    --disable-newgal \
    --enable-purefbgfx \
    --enable-nativegal \
    $rot_dir \
    --enable-ipaqial \
    --disable-nativeial \
    --disable-pcxsupport \
    --disable-lbmsupport \
    --disable-tgasupport \
    --disable-qpfsupport \
    --disable-ttfsupport \
    --disable-type1support \
    --disable-latin9support \
    --disable-gbksupport \
    --disable-big5support \
    --disable-unicodesupport \
    --disable-pngsupport \
    --disable-micemoveable \
    --disable-cursor \
    --disable-imegb2312 \
    --disable-imegb2312pinyin \
    --disable-savebitmap \
    --disable-savescreen \
    --disable-aboutdlg \
    --disable-ext-fullgif \
    --enable-flatstyle \
    --disable-dblclk
}

echo Please select a model for your iPAQ.

OPTIONS="H3600 H3800 Quit"
select opt in $OPTIONS; do
    if [ "$opt" = "Quit" ]; then
        echo Quit...
        exit 0
    elif [ "$opt" = "H3600" ]; then
        rot_dir="--enable-coortrans_ccw"
        config
        exit 0
    elif [ "$opt" = "H3800" ]; then
        rot_dir="--enable-coortrans_cw"
        config
        exit 0
    else
        echo Please select a model for your iPAQ.
    fi
done

