#ifndef  _CS_APP_CHINESE_H_
#define  _CS_APP_CHINESE_H_

#include "mwsetting.h"

#if defined (USE_CHINESE_BIG5_ENCODE)


static	U8* 	ChineseString[CSAPP_STR_MAX]={
"",
"ä¸»èœå–®",
"ç¯€ç›®æœç´¢",
"é »é“ç·¨è¼¯",
"è¨­ç½®",
"ç³»çµ±ä¿¡æ¯",
"é›»è¦–ç¯€ç›®",
"å»£æ’­ç¯€ç›®",
"å–œæ„›ç¯€ç›®",
"ç„¡ç¯€ç›®",
"ç¯€ç›®åˆ—è¡¨ç©º...",
"LCN",
"é »é“åç¨±",
"é–å®š",
"å–œæ„›",
"é›»å¹³",
"è³ªé‡",
" HD",
"H.264",
" AC3",
" CC",
"ç¯€ç›®é€²åº¦",
"æœç´¢æ¨¡å¼",
"   é »ç‡",
"   å¸¶å¯¬",
"MHz",
"é–‹å§‹",
"æ‰‹å‹•æœç´¢",
"è‡ªå‹•æœç´¢",
"ç¶²çµ¡æœç´¢",
"æœç´¢é€²åº¦",
"é›»è¦–ç¯€ç›®æ•¸",
"å»£æ’­ç¯€ç›®æ•¸",
"é›»è¦–ç·¨è¼¯",
"å»£æ’­ç·¨è¼¯",
"   AVè¨­ç½®  ",
"  ç³»çµ±è¨­ç½®",
"  æ™‚é–“è¨­ç½®",
"  å¯†ç¢¼è¨­ç½®",
"æ¢å¾©å‡ºå» è¨­ç½®",
"ç”¢å“å‹è™Ÿ",
"ç¡¬ä»¶ç‰ˆæœ¬",
"è»Ÿä»¶ç‰ˆæœ¬",
"é›»å­ç¯€ç›®æŒ‡å—",
"é »é“åç¨±",
"ç„¡è©³ç´°ä¿¡æ¯...",
"ç¯€ç›®åç¨±",
"  é å®š",
"å‰ä¸€å¤©",
"åä¸€å¤©",
"ç°¡ä»‹",
"æ˜ŸæœŸä¸€",
"æ˜ŸæœŸäºŒ",
"æ˜ŸæœŸä¸‰",
"æ˜ŸæœŸå››",
"æ˜ŸæœŸäº”",
"æ˜ŸæœŸå…­",
"æ˜ŸæœŸæ—¥",
"éŸ³é‡",
"éŸ³é »è¨­ç½®",
"éŸ³é »é¸æ“‡",
"è²é“é¸æ“‡",
"ç«‹é«”è²",
"å·¦è²é“",
"å³è²é“",
"å–®è²é“",
"é »ç‡ï¼š",
"ä¿¡è™Ÿç‹€æ…‹:",
"ç„¡ä¿¡è™Ÿ",
"ç„¡ç¯€ç›®",
"ç¯€ç›®åŠ å¯†",
"åœ–æ–‡èªè¨€é¸æ“‡",
"å­—å¹•èªè¨€é¸æ“‡",
"å¯¬é«˜æ¯”",
"è½‰æ›æ–¹å¼",
"è¼¸å‡ºé¡å‹",
"è¼¸å‡ºæ¨¡å¼",
"4:3",
"16:9",
"è‡ªå‹•",
"Letterbox",
"PanScan",
"Full",
#if 0
"480p",
"576i",
"576p",
"720p",
"1080i",
"1080p",
#endif
"CVBS",
"YC",
"YCbCr",
"YPbPr",
"RGB",
"HDMI",
"èœå–®èªè¨€",
"é‚è¼¯é »é“è™Ÿ",
"ç«¥é–å¹´é½¡",
"æ™‚å€",
"æ™‚é–“æ¨¡å¼",
"ç¶²çµ¡",
"è‡ªå®šç¾©",
"æ—¥æœŸ",
"æ™‚é–“",
"OK: ä¿å­˜é€€å‡ºï¼ŒMENU/EXIT: å–æ¶ˆä¿®æ”¹ä¸¦é€€å‡º",
"æ™‚é–“å€åŸŸ",
"èœå–®é€æ˜åº¦",
"è‡ªå‹•å®šç¾©",
"é‹ç‡Ÿå•†å®šç¾©",
"å¯†ç¢¼ç‹€æ…‹",
" æ‰“é–‹",
" é—œé–‰",
"èˆŠå¯†ç¢¼",
"æ–°å¯†ç¢¼",
"ç¢ºèªæ–°å¯†ç¢¼",
"å¯†ç¢¼è¼¸å…¥",
" P I N",
"    ç•¶å‰å¯†ç¢¼éŒ¯èª¤",
"  å…©æ¬¡è¼¸å…¥ä¸ä¸€è‡´",
"  è¨­ç½®æ–°å¯†ç¢¼æˆåŠŸ",
"è­¦å‘Š!",
"åŸ·è¡Œè‡ªå‹•æœç´¢å°‡æ¸…ç©ºç¯€ç›®åˆ—è¡¨ï¼Œ\næ˜¯å¦ç¹¼çºŒï¼Ÿ",
"æ•¸æ“šå·²ç¶“æ›´æ”¹ï¼Œæ˜¯å¦ä¿å­˜?",
"ç¢ºå®š",
"å–æ¶ˆ",
"æŒ‰OKéµç¢ºå®š,EXITéµå–æ¶ˆ",
"åˆªé™¤",
"é–å®š",
"å–œæ„›",
"æ’åº",
"æ¢å¾©å‡ºå» è¨­ç½®å°‡æ¸…é™¤æ‰€æœ‰ç¯€ç›®ä¿¡æ¯å’Œç”¨æˆ¶è¨­ç½®ï¼Œç¢ºèªå—?",
"æ¢å¾©å‡ºå» è¨­ç½®ä¸­ï¼Œè«‹ä¸è¦æ–·é›»!",
"SPDIF",
"PCM",
"AC3"


};

#elif defined(USE_CHINESE_GB_ENCODE)

static const U8* 	ChineseString[CSAPP_STR_MAX]={
"",
"Ö÷²Ëµ¥",
"½ÚÄ¿ËÑË÷",
"ÆµµÀ±à¼­",
"ÉèÖÃ",
"ÏµÍ³ĞÅÏ¢",
"µçÊÓ½ÚÄ¿",
"¹ã²¥½ÚÄ¿",
"Ï²°®½ÚÄ¿",
"ÎŞ½ÚÄ¿",
"½ÚÄ¿ÁĞ±í¿Õ...",
"LCN",
"ÆµµÀÃû³Æ",
"Ëø¶¨",
"Ï²°®",
"µçÆ½",
"ÖÊÁ¿",
" HD",
"H.264",
" AC3",
" CC",
"½ÚÄ¿½ø¶È",
"ËÑË÷Ä£Ê½",
"   ÆµÂÊ",
"   ´ø¿í",
"MHz",
"¿ªÊ¼",
"ÊÖ¶¯ËÑË÷",
"×Ô¶¯ËÑË÷",
"ÍøÂçËÑË÷",
"ËÑË÷½ø¶È",
"µçÊÓ½ÚÄ¿Êı",
"¹ã²¥½ÚÄ¿Êı",
"µçÊÓ±à¼­",
"¹ã²¥±à¼­",
"   AVÉèÖÃ  ",
"  ÏµÍ³ÉèÖÃ",
"  Ê±¼äÉèÖÃ",
"  ÃÜÂëÉèÖÃ",
"»Ö¸´³ö³§ÉèÖÃ",
"²úÆ·ĞÍºÅ",
"Ó²¼ş°æ±¾",
"Èí¼ş°æ±¾",
"µç×Ó½ÚÄ¿Ö¸ÄÏ",
"ÆµµÀÃû³Æ",
"ÎŞÏêÏ¸ĞÅÏ¢...",
"½ÚÄ¿Ãû³Æ",
"  Ô¤¶¨",
"Ç°Ò»Ìì",
"ºóÒ»Ìì",
"¼ò½é",
"ĞÇÆÚÒ»",
"ĞÇÆÚ¶ş",
"ĞÇÆÚÈı",
"ĞÇÆÚËÄ",
"ĞÇÆÚÎå",
"ĞÇÆÚÁù",
"ĞÇÆÚÈÕ",
"ÒôÁ¿",
"ÒôÆµÉèÖÃ",
"ÒôÆµÑ¡Ôñ",
"ÉùµÀÑ¡Ôñ",
"Á¢ÌåÉù",
"×óÉùµÀ",
"ÓÒÉùµÀ",
"µ¥ÉùµÀ",
"ÆµÂÊ£º",
"ĞÅºÅ×´Ì¬:",
"ÎŞĞÅºÅ",
"ÎŞ½ÚÄ¿",
"½ÚÄ¿¼ÓÃÜ",
"Í¼ÎÄÓïÑÔÑ¡Ôñ",
"×ÖÄ»ÓïÑÔÑ¡Ôñ",
"¿í¸ß±È",
"×ª»»·½Ê½",
"Êä³öÀàĞÍ",
"Êä³öÄ£Ê½",
"4:3",
"16:9",
"  ×Ô¶¯",
"Letterbox",
" PanScan",
"  Full",
#if 0
"480p",
"576i",
"576p",
"720p",
"1080i",
"1080p",
#endif
"CVBS",
"YC",
"YCbCr",
"YPbPr",
"RGB",
"HDMI",
"²Ëµ¥ÓïÑÔ",
"Âß¼­ÆµµÀºÅ",
"Í¯ËøÄêÁä",
"Ê±Çø",
"Ê±¼äÄ£Ê½",
"ÍøÂç",
"×Ô¶¨Òå",
"ÈÕÆÚ",
"Ê±¼ä",
"OK: ±£´æÍË³ö£¬MENU/EXIT: È¡ÏûĞŞ¸Ä²¢ÍË³ö",
"Ê±¼äÇøÓò",
"²Ëµ¥Í¸Ã÷¶È",
"×Ô¶¯¶¨Òå",
"ÔËÓªÉÌ¶¨Òå",
"ÃÜÂë×´Ì¬",
" ´ò¿ª",
" ¹Ø±Õ",
"¾ÉÃÜÂë",
"ĞÂÃÜÂë",
"È·ÈÏĞÂÃÜÂë",
"ÃÜÂëÊäÈë",
" P I N",
"    µ±Ç°ÃÜÂë´íÎó",
"  Á½´ÎÊäÈë²»Ò»ÖÂ",
"  ÉèÖÃĞÂÃÜÂë³É¹¦",
"¾¯¸æ!",
"Ö´ĞĞ×Ô¶¯ËÑË÷½«Çå¿Õ½ÚÄ¿ÁĞ±í£¬\nÊÇ·ñ¼ÌĞø£¿",
"Êı¾İÒÑ¾­¸ü¸Ä£¬ÊÇ·ñ±£´æ?",
"È·¶¨",
"È¡Ïû",
"°´OK¼üÈ·¶¨,EXIT¼üÈ¡Ïû",
"É¾³ı",
"Ëø¶¨",
"Ï²°®",
"ÅÅĞò",
"»Ö¸´³ö³§ÉèÖÃ½«Çå³ıËùÓĞ½ÚÄ¿ĞÅÏ¢ºÍÓÃ»§ÉèÖÃ£¬È·ÈÏÂğ?",
"»Ö¸´³ö³§ÉèÖÃÖĞ£¬Çë²»Òª¶Ïµç!",
"SPDIF",
"  PCM",
"  AC3"
};
#elif defined(USE_Portuguese_ENCODE)

static const U8* 	ChineseString[CSAPP_STR_MAX]={
"",
"Main Menu",
"Instalação",//"Install",
"Edição de Programa",//"Edit Program",
"Ajuste de Sistema",//"System Setting",
"Informação do Sistema",//"System Info",
"Canal de TV",//"TV Channel",
"Canal de Rádio",//"Radio Channel",
"Canal FAV",//"FAV Channel",
"No channel",
"No program...",
"LCN",
"Nome",//"Name",
"Lock",
"Love",
"Level",
"SNR",
"HD",
"H264",
"AC3",
"CC",
"Progress",
"Modo",
"Frequencia",//"Frequency",
"Banda de",//"Bandwidth",
"MHz",
"Start",
" Manual",
"  Auto",
"  NIT",
"Progress",
"TV number",
"Radio Number",
"Edição de TV ",//"Edit TV",
"Edição Rádio",//"Edit Radio",
"Ajuste AV",//"AV Setting",
"Ajuste do Sistema",//"Sys Setting",
"Ajustes de Tempo",//"Time Setting",
"Ajuste de PIN",//"Pin Setting",
"Definição de Fábrica",//"Factory Def",
"Tipo",//"Type No.",
"Versão do HW",//"HW Version",
"Versão do SW",//"SW Version",
"EPG",
"Channel name",
"No detail information...",
"Program name",
"Book",
"Pre Day",
"Next Day",
"Desc.",
"Mon.",
"Thes.",
"Wed.",
"Thurs.",
"Fri.",
"Sat.",
"Sun.",
"Volume",
"Audio setting",
"Audio lang",
"Audio track",
"Stereo",
"Left",
"Right",
"Mono",
"Frequency:",
"Nível do Sinal",//"Signal Status:",
"No Signal",
"No Service",
"Service Encrypt",
"Teletext language",
"Linguagem da Legenda",//"Subtitle language",
"Razão de Espectro",//"Aspect ratio",
"Aspect mode",
"Definição Vídeo",//"Video def",
"Video output",
"4:3",
"16:9",
"Automático",//"Automatic",
"Letterbox",
" PanScan",
"  Full",
#if 0
"480p",
"576i",
"576p",
"720p",
"1080i",
"1080p",
#endif
"CVBS",
"YC",
"YCbCr",
"YPbPr",
"RGB",
"HDMI",
"Linguagem",//"Menu lang",
"Logic CH Num",
"Parent rate",
"Zona de Tempo",//"Time Zone",
"Modo de Tempo",//"Time Mode",
"Rede",//"Net",
"Local",
"Data",//"Date",
"Hora",//"Time",
"OK: save&exit, MENU/EXIT: cancel&exit",
"Time region",
"Transparência",//"Transparency",
"Appearing order",
"Operator defined",
"Pin Status",
"Habilitado",//"Enable",
"Desabilitado",//"Disable",
"PIN Anterior",//"Old pin",
"Novo PIN",//"New pin",
"Confirme PIN",//"Confirm pin",
"PIN de entrada",//"Input PIN",
" P I N",
"Old password Error.",
"Confirm password Error",
"New Password success",
"Warning",
"This will clear all services, \ncontinue?",
"Data is changed, save?",
"OK",
"CANCEL",
"Press OK to comfirm, Press EXIT \nto cancel",
"Remove",//"Delete",
"Trava",//"Lock",
"Favorito",//"Fav",
"Ordena",//"Sort",
"Voce tem certeza de apagar \ntodos os serviços e ajustes \ndo usuário ?",//"Are you sure to clear all \nservices and reset user \nsettings?",
"Loading default settings, please don't shut power!",
"SPDIF",
"PCM",
"AC3"

};

#endif

#endif
/*   E O F  */
