#ifndef _CS_APP_GERMAN_H_
#define _CS_APP_GERMAN_H_

#include "mwsetting.h"


static U8 * GermanString [CSAPP_STR_MAX] = {
"",
"Hauptmenu",
"Installation",
"Install & Suchen",
"Satelliten-Einstellung",
"TP-Einstellung",
"Edit Program",
"System Setting",
"System Information",
"Alle Satelliten-TV",
"Alle Satellite Radio",
"FAV-Kanal",
"Kein Kanal ...",
"Kein Programm ...",
"LCN",
"Name",
"Lock",
"Liebe",
"Level",
"SNR",
"HD",
"H264",
"AC3",
"CC",
"Progress",
"Mode",
"Frequenz",
"Bandbreite",
"MHz",
"Start",
"Manuell",
"Auto",
"NIT",
"Progress",
"TV-Nummer",
"Radio Number",
"Edit TV",
"Edit Radio",
"AV-Einstellung",
"System Setting",
"Zeiteinstellung",
"Parental Control",
"Factory Reset",
"Art-Nr",
"HW-Version",
"SW-Version",
"Timer", // ??kb: Mar 25
"EPG", // ??kb: Mar 25
"Simple", // ??kb: Mar 25
"Geplante", // ??kb: Mar 25
"Current", // ??kb: Mar 25
"Weiter", // ??kb: Mar 25
"Nein Detailinformationen ...", // ??kb: Mar 25
"Pre Day",
"Next Day",
"Desc.",
"Mo",
"Di",
"Mi",
"Do",
"Fr",
"Sa",
"So",
"Volume",
"Audio-Einstellung",
"Audio lang",
"Audio Track",
"Stereo",
"Links",
"Rechts",
"Mono",
"Frequenz",
"Symbol Rate",
"Polaritat",
"H",
"V",
"Signal Status:",
"Kein Signal",
"Kein Service",
"Scramble",
"Teletext",
"Untertitel",
"Aspect Ratio",
"Aspect-Modus",
"Video def",
"Video-Ausgang",
"4:3",
"16:9",
"Automatik",
"Letterbox",
"PanScan",
"Voll",
"CVBS",
"YC",
"YCbCr",
"YPbPr",
"RGB",
"HDMI",
"Sprache einstellen",
"Logic CH Num",
"Parent-Rate",
"Zeitzone",
"Time-Modus",
"Satellite Time",
"Local Time",
"Datum",
"Time",
"OK: Save & Exit,\nMENU / EXIT: abbrechen & Exit ",  /* By KB Kim 2011.05.06 */
"Zeit-Raum",
"Transparenz",
"Erscheinungsreihenfolge",
"Operator definiert",
"Lock-Status",
"Boot Lock",
"Menu sperren",
"Channel Edit Lock",
"Channel Lock",
"Favorite Lock",
"Kennwort andern",
"Enable",
"Disable",
"Alte PIN",
"Neue Stift",
"PIN bestatigen",
"Passwort eingeben",
"Passwort",
"Altes Passwort-Fehler.",
"Passwort bestatigen Fehler",
"Neues Passwort Erfolg",
"Warnung",
"Das wird klar, alle Dienste, \nFortfahren?",
"Daten geandert wird, zu retten?",
"OK",
"Abbrechen",
"Speichern",
"Drucken Sie OK, um zu uberprufen, \nDrucken EXIT zum Abbrechen",
"Loschen",
"Lock",
"Lock",
"Fav",
"Sortieren",
"Diese Operation wird geladen \n Standard und loschen Sie alle \n der Kanale, die Benutzer hat, \n fortfahren?",
"Einlegen von Standardeinstellungen, \n Sie bitte nicht, Macht zu!",
"Diese Operation wird Datensicherung \n - Satellit & tp & Channel - \n fortfahren?",
"Diese Operation wird restore \n Backup-Daten auf Datenbank \n -. Sat-& tp & Channel -? \n fortsetzen",
"Diese Operation wird hinzufugen \n Neue Plug-In-Programm \n & Reboot System",
"SPDIF",
"PCM",
"AC3",
"Strength",
"Qualitat",
"OSD Setting",
"Netzwerkeinstellungen",
"Recorded File",
"Recorded Config",
"File Tools",
"USB-Gerat entfernen",
"Storage Information",
"MP3-Player",
"Upgrade",
"Common Interface",
"Conditional Access",
"Backup",
"Backup wiederherstellen",
"Plug-in",
"Summer Time",
"Jahr",
"Monat",
"Day",
"Stunde",
"Minute",
"On",
"Aus",
"Video-Einstellung",
"Bright",
"Kontrast",
"Farbe",
"Media",
"Tool",
"Info Banner Time",
"DHCP",
"DHCP-Einstellung",
"IP Address",
"Subnet Mask",
"Gateway",
"Primarer DNS",
"Secondary DNS",
"Third DNS",
"MAC-Adresse",
"Konnektivitat",
"Satellite",
"TP auswahlen",
"LNB-Typ",
"LNB Power",
"22K Tone",
"High Frequency",
"Low Frequency",
"DiSEqC-Einstellung",
"Scan Type",
"Multi Sat",
"Single Sat",
"Wahlen Satellite",
"Transponder wahlen",
"ToneBurst",
"Umbenennen",
"Scan",
"Neue Transponder",
"Manual Channel Zusatz",
"Finden",
"Erweitert",
"Bearbeiten",
"Transponder",
"Video PID",
"Audio PID",
"PCR PID",
"Service-ID",
"Same TP",
"Invalid Data",
"Keine Daten", // ??von KB: 20100406
"Nein TP-Daten", // ??von KB: 20110115
"Sind Sie sicher?",
"Move",
"Alle",
"TV",
"Radio",
"Loschen aktuellen TP",
"Select",
"Jump",
"Von A bis Z sortieren",
"Z-A Sort",
"FTA-CAS Sortieren",
"CAS-FTA Sortieren",
"SD-HD Sortieren",
"HD-SD-Sort",
"Restore Normal",
"Alle Satelliten",
"Achtung",
"Jetzt sparen ... \nDon't beliebige Taste drucken!",
"Pause Screen",
"Black Screen",
"Channel Typ andern",
"Nicht verwenden",
"Benutzen",
"Get DHCP",
"Jetzt Holen DHCP Data \nWait Einige Zweite ...",
"FAIL Holen DHCP Data \nChecking Netzwerk Umwelt",
"Ungultige IP-Adresse .. \nVersuchen Again!",
"Test PING",
"Ping ..... DNS",
"Ping ..... IP",
"PING Fail Check Network",
"DNS PING Fail, IP-PING OK \nUberprufen DNS-Adresse",
"OK PING !!!!",
"Keine",
"Sprache",
"Ungultige Channel Number ...",
"Total Size",
"Gebraucht Gro©¬e",
"Verfugbare Space",
"Storage Type",
"Storage Vender",
"Storage Product",
"Storage Serial Number",
"Storage Format",
"Alle loschen TP",
"Bitte warten",
"Position Nr.",
"Goto X",
"Schritt Move",
"Auto Move",
"Limit-Einstellung",
"West-Set Limit",
"Ost-Limit einstellen",
"Goto Referenz",
"Neuberechnung",
"Wahlen Sie zuerst Satellite",
"USALS-Einstellung",
"Satellite Longitude",
"Lokale Longitude",
"Lokale Latitude",
"Andern Longitude",
"Unicable-Einstellung",
"Unicable LNB Select",
"Position setzen",
"Ubertragungskanal",
"Transmission Frequenz",
"Alle Sender Loschen",
"Delete Channel by Satellite",
"Tastatur",
"Numerische Tastatur",
"Search Condition",
"Transponder Zusatz",
"Channel Zusatz",
"Time Shift",
"Time Shift Aufnahme",
"Stream Type",
"Time Jump",
"Jetzt PVR Recording \nDrucken Stop First",
"Jetzt spielen PVR \nDrucken Stop First",
"Um interne Flesh",
"Um USB",
"Von der Internen Flesh",
"Von der Standard-Daten",
"Von USB",
"Card-Status",
"Karte",
"Datei nicht gefunden",
"CAS Detailinformationen",
"Recall",
"Single",
"Multi",
"Model-Typ",
"UBOOT Version",
"Kernel-Version",
"Rootfs Version",
"SW Main Version",
"Default Sa TP Version",
"Standard-Datenbank",
"Video-Hintergrund",
"Audio-Hintergrund",
"Kopieren",
"Einfugen",
"Same Folder",
"Es ist die gleiche Datei",
"Hinzufugen",
"Abscannen ..",
"Gesperrt",
"Unlock",
"Extend Channel Information",
"Netzwerk-Typ",
"Newcamd Client",
"Newcamd Server",
"CCCam",
"Server-Nummer",
"URL",
"Server Port",
"User",
"DES-Key",
"CA-Typ",
"Auto Connect",
"Login",
"Start",
"Font",
"Schriftgrad",
"Englisch",
"Turkisch",
"Franzosisch",
"Deutsch",
"Griechen",
"Arabisch",
"Perser",
"Internet Time",
"DNS-Methode",
"Slot leer",
"Eingefugt Card",
"Datei zu erforschen",
"Datenbank",
"Alle Flash Backup",
"Alle Flash Restore",
"No Files",
"Nein Wahlen Sie Datei ",
"Aufnahme-Fehler",
"Playing Fehler",
"Weiter?",
"Nein",
"On / Off",
"Typ",
"Wiederholen",
"Kanal",
"End",
"Dauer",
"Power Off-Modus",
"Sleep Mode",
"Real Off",
"Time Display auf Standby",
"Reboot System \nSoll?,"
"System Reboot",
"Erweitert",
"Normal",
"Kanal-Liste fur Typ",
"Wake Up",
"Sleep",
"Record",
"Once",
"Everyday",
"Jede Woche",
"Spiel",
"Goodbye ...",
"Gut .. Nachste?",
"Stage",
"Neustart",
"Zuruck",
"Next Stage",
"Zuruck Stage",
"Januar",
"Februar",
"Marz",
"April",
"May",
"Juni",
"Juli",
"August",
"September",
"Oktober",
"November",
"Dezember",
"Kalender",
"Nachsten Monat",
"Zuruck Monats",
"Next Year",
"Zuruck Jahres",
"Change-Partition",
"Partition",
"Titel",
"Kunstler",
"Album",
"Edit BISS",
"Move Dish",
"Herunterladen ..",
"Get List .. FAIL! \n Retry !",
"Download-Datei .. FAIL! \n einmal!", /* By KB Kim : 2011.05.07*/
"Upgrade .. FAIL! \n Retry !",
"Do You Want to Upgrade ?", /* By KB Kim : 2011.05.07*/
"Space",
"Skin",
"Reset",
"Sat A",
"Sat B",
"Menu Animation",
"Heart Bit",
"FTA + CAS-Suche",
"FTA + CAS NIT-Suche",
"FTA Search",
"FTA NIT-Suche",
"FTA + CAS Blind Search",
"FTA Blind Search",
"DiSEqC Port",
"DiSEqC Motor",
"USALS",
"Unicable",
"System Ready",
"Boot Block",
"Kernel",
"Plug-In",
"Application 1",
"Application 2",
"Root-Dateisystem",
"Fertig stellen",
"Boot-Block-Upgrade",
"Kernel Upgrade",
"Plug-In Aktualisieren",
"Application 1 Aktualisieren",
"Application 2 Aktualisieren",
"Root-Dateisystem Aktualisieren",
"Finishing",
"USB",
"NETZWERK",
"Software-Upgrade ... Bitte warten",
"OSCAM Setting",
"Port End",
"Username",
"Key",
"Status",
"CCCamd",
"Newcamd",
"Connect",
"Disconnect",
"Connected",
"Not Connected",
"Server-Nummer",
"Protokoll",
"Port Start",
"DES-Key",

"Unbekannt", /* Durch KB 1022.04.09 */
"Can't change \nPincode Fehler! Wiederholen?",
"Can't change \nNeue Code Error! Wiederholen?",
"Test",
"Wenn ein Upgrade nicht in 10 Minuten fertig,\npls Power-Off und auf manuell", /* By KB Kim : 2011.05.07*/
"USB-Gerat anschlie©¬en ...",
"USB-Gerat MOUNT",
"USB-Gerat TRENNEN ...",
"USB-Gerat UNMOUNT",
"All Clear",
//"Speichern",
"Back Space",
"NAME",
"Gro©¬e",
"Record Time",
"Programm",
//"Dauer",
"Endzeit",
//"TIME",
"Capslock",
"Caps",
"Del",
"SMART-Karte einlegen ...",
"SMART card Remove ...",
"Install Plug-In", /* By KB Kim for Plugin Setting : 2011.05.07 */
"Install PlugIn .. FAIL !!\n Retry !!", /* By KB Kim for Plugin Setting : 2011.05.07 */
"Do You Want to Install?", /* By KB Kim for Plugin Setting : 2011.05.07 */
"Add Server", /* By KB Kim for Plugin Setting : 2011.05.07 */
"Server Data Full", /* By KB Kim for Plugin Setting : 2011.05.07 */
"Delete Server",    /* By KB Kim for Plugin Setting : 2011.05.25 */
"Extend" ,
"Detail Information",
"No Module Inserted",
"Module Initialising......",
"Module OK !",
"Change Focus",
"Locked\nChannel",
"Site List",		/* By KB Kim for Plugin Site List : 2011.09.20 */
"Can Not Delete",		/* By KB Kim for Plugin Site List : 2011.09.20 */
"Can Not Add",		/* By KB Kim for Plugin Site List : 2011.09.20 */
"Remove channel from Favorite",
"Uygulama Baþlýyor...",
"Installing Plugin...",
"Plugin Installed Succesfully!!",
"Currently Streaming \n Press STOP first!!",
"Streaming Starting..."
};
#endif
/* E O F */


