#!/bin/sh

# this script builds all chipbox-pars in a docker container

for dir in open_sources csapi mvapi Mvapp oscam
do
	echo "****************"
	echo "**Building $dir**"
	sleep 1
	cd $dir
	./ba
	cd ..
done
