#ifndef  _CS_AV_SETTING_H_
#define  _CS_AV_SETTING_H_

typedef enum
{
	AV_ASPECT_RATIO = 0,
	AV_ASPECT_MODE,
	AV_VIDEO_DEFINITION,
	AV_VIDEO_OUTPUT,
	AV_AUDIO_SPDIF_OUTPUT,
	AV_SETTING_ITEM_MAX
} eMV_Setting_Items;


enum
{
	CS_APP_ASPECT_4_3 = 0,
	CS_APP_ASPECT_16_9,
	CS_APP_ASPECT_AUTO,
	CS_APP_ASPECT_RATIO_NUM
};

enum
{
	CS_APP_ASPECT_FULL = 0,
	CS_APP_ASPECT_LETTER_BOX,
	CS_APP_ASPECT_PAN_SCAN,
	CS_APP_ASPECT_MODE_NUM
};

#if 1
enum
{
	CS_APP_DEFINITION_480I = 0,
	CS_APP_DEFINITION_576I,
	CS_APP_DEFINITION_576P,
	CS_APP_DEFINITION_720P,
	CS_APP_DEFINITION_1080I,
	//CS_APP_DEFINITION_1080P,
	CS_APP_DEFINITION_AUTO,
	CS_APP_DEFINITION_NUM
};
#else
#define CS_APP_DEFINITION_NUM   5
#endif

#if 0 /* By KB Kim 2010.08.31 */
enum
{
	CS_APP_OUTPUT_CVBS = 0,
	CS_APP_OUTPUT_YC,
	CS_APP_OUTPUT_YCBCR,
	CS_APP_OUTPUT_YPBPR,
	CS_APP_OUTPUT_RGB,
	CS_APP_OUTPUT_HDMI,
	CS_APP_OUTPUT_NUM
};
#else
enum
{
	CS_APP_OUTPUT_RGB = 0,
	CS_APP_OUTPUT_YPBPR,
	// CS_APP_OUTPUT_YC,
	CS_APP_OUTPUT_NUM
};
#endif

enum
{
	CS_APP_AUDIO_SPDIF_OUTPUT_AUTO =0,
	CS_APP_AUDIO_SPDIF_OUTPUT_PCM,
	CS_APP_AUDIO_SPDIF_OUTPUT_AC3,
	CS_APP_AUDIO_SPDIF_OUTPUT_NUM
};

CSAPP_Applet_t	CSApp_AVSetting(void);

#endif
