#ifndef  _CS_BACKUP_H_
#define  _CS_BACKUP_H_

CSAPP_Applet_t	CSApp_Backup(void);

#define BACKUP_WARNING_X		440
#define	BACKUP_WARNING_Y		200
#define	BACKUP_WARNING_DX		400
#define	BACKUP_WARNING_DY		30
#define	BACKUP_WARNING_MSG_X	BACKUP_WARNING_X
#define	BACKUP_WARNING_MSG_Y	260
#define	BACKUP_WARNING_MSG_DX	BACKUP_WARNING_DX
#define	BACKUP_WARNING_MSG_DY	260
#define BACKUP_SUB_TITLE1_X		300
#define BACKUP_SUB_TITLE1_Y		460
#define BACKUP_SUB_TITLE2_Y		530
#define	BACKUP_SAT_BUTTON_X		540
#define	BACKUP_SAT_BUTTON_Y		450
#define	BACKUP_SAT_BUTTON_DX	300
#define	BACKUP_CH_BUTTON_X 		BACKUP_SAT_BUTTON_X
#define BACKUP_CH_BUTTON_Y		480
#define	BACKUP_ALL_BUTTON_X 	BACKUP_SAT_BUTTON_X
#define BACKUP_ALL_BUTTON_Y		510

typedef enum
{
	EN_BACKUP_MSG_INTER= 0,
	EN_BACKUP_MSG_USB,
	EN_BACKUP_MSG_ALL,
	EN_BACKUP_MSG_MAX
}EN_BACKUP_MSG;

typedef enum
{
	EN_RESTORE_MSG_INTER= 0,
	EN_RESTORE_MSG_DEFAULT,
	EN_RESTORE_MSG_USB,
	EN_RESTORE_MSG_MAX
}EN_RESTORE_MSG;

#endif

