#ifndef  _CS_APP_TIME_SETTING_H_
#define  _CS_APP_TIME_SETTING_H_

#define 	CS_APP_TIME_ZONE_NUM    	CSAPP_TIME_ZONE_MAX_NUM
#define 	CS_APP_TIME_SETTING_ITEM_TOTAL_NUM 4

#define 	TIME_SETTING_YMD_STR_LEN 	11
#define 	TIME_SETTING_HM_STR_LEN  	6

typedef enum
{
	TIME_ITEM_MODE=0,
	TIME_ITEM_ZONE,
	TIME_ITEM_SUMMER,
	TIME_ITEM_YEAR,
	TIME_ITEM_MONTH,
	TIME_ITEM_DAY,
	TIME_ITEM_HOUR,
	TIME_ITEM_MINUTE,
	TIME_ITEM_MAX
}	eMV_Time_ItemID;

typedef enum
{
	CS_APP_TIME_LOCAL = 0,
	CS_APP_YMD,
	CS_APP_HM,
	CS_APP_TIME_SETTING_ITEM_NUM_LOCAL
}tTIME_Setting_Items_Local;

typedef enum
{
	CS_APP_TIME_NET = 0,
	CS_APP_TIME_ZONE_NOW,
	CS_APP_TIME_SETTING_ITEM_NUM_NET
}tTIME_Setting_Items_Net;

typedef struct
{
	char ymd[TIME_SETTING_YMD_STR_LEN];
	int current_char;
}tTIME_SETTING_YMD;

typedef struct
{
	char hm[TIME_SETTING_HM_STR_LEN];
	int current_char;
}tTIME_SETTING_HM;

enum
{
	CS_APP_TIME_MODE_NET = 0,
	CS_APP_TIME_MODE_LOCAL,
	CS_APP_TIME_MODE_UTC,
	CS_APP_TIME_MODE_NUM
};

enum
{
	CS_APP_TIME_ZONE_M_12 = 0,
	CS_APP_TIME_ZONE_M_11_5,
	CS_APP_TIME_ZONE_M_11,
	CS_APP_TIME_ZONE_M_10_5,
	CS_APP_TIME_ZONE_M_10,
	CS_APP_TIME_ZONE_M_09_5,
	CS_APP_TIME_ZONE_M_09,
	CS_APP_TIME_ZONE_M_08_5,
	CS_APP_TIME_ZONE_M_08,
	CS_APP_TIME_ZONE_M_07_5,
	CS_APP_TIME_ZONE_M_07,
	CS_APP_TIME_ZONE_M_06_5,
	CS_APP_TIME_ZONE_M_06,
	CS_APP_TIME_ZONE_M_05_5,
	CS_APP_TIME_ZONE_M_05,
	CS_APP_TIME_ZONE_M_04_5,
	CS_APP_TIME_ZONE_M_04,
	CS_APP_TIME_ZONE_M_03_5,
	CS_APP_TIME_ZONE_M_03,
	CS_APP_TIME_ZONE_M_02_5,
	CS_APP_TIME_ZONE_M_02,
	CS_APP_TIME_ZONE_M_01_5,
	CS_APP_TIME_ZONE_M_01,
	CS_APP_TIME_ZONE_M_00_5,
	CS_APP_TIME_ZONE_00,
	CS_APP_TIME_ZONE_P_00_5,
	CS_APP_TIME_ZONE_P_01,
	CS_APP_TIME_ZONE_P_01_5,
	CS_APP_TIME_ZONE_P_02,
	CS_APP_TIME_ZONE_P_02_5,
	CS_APP_TIME_ZONE_P_03,
	CS_APP_TIME_ZONE_P_03_5,
	CS_APP_TIME_ZONE_P_04,
	CS_APP_TIME_ZONE_P_04_5,
	CS_APP_TIME_ZONE_P_05,
	CS_APP_TIME_ZONE_P_05_5,
	CS_APP_TIME_ZONE_P_06,
	CS_APP_TIME_ZONE_P_06_5,
	CS_APP_TIME_ZONE_P_07,
	CS_APP_TIME_ZONE_P_07_5,
	CS_APP_TIME_ZONE_P_08,
	CS_APP_TIME_ZONE_P_08_5,
	CS_APP_TIME_ZONE_P_09,
	CS_APP_TIME_ZONE_P_09_5,
	CS_APP_TIME_ZONE_P_10,
	CS_APP_TIME_ZONE_P_10_5,
	CS_APP_TIME_ZONE_P_11,
	CS_APP_TIME_ZONE_P_11_5,
	CS_APP_TIME_ZONE_KIND_NUM
};

CSAPP_Applet_t CSApp_TimeSetting(void);

#endif

