#ifndef  _CS_APP_FINDER_H_
#define  _CS_APP_FINDER_H_

#define CS_FINDER_MAX_NUM						3

#define FINDER_KEYBOARD_STARTX					700
#define FINDER_KEYBOARD_STARTY					140
#define FINDER_KEYBOARD_STARTDX					360
#define FINDER_KEYBOARD_STARTDY					WINDOW_DY - 90//16*16
#define FINDER_KEYBOARD_KEY_OFFSET 				30
#define FINDER_KEYBOARD_NUM_KEY_STARTX			FINDER_KEYBOARD_STARTX + FINDER_KEYBOARD_KEY_OFFSET
#define FINDER_KEYBOARD_CHAR_KEY_STARTX			FINDER_KEYBOARD_NUM_KEY_STARTX
#define FINDER_KEYBOARD_NUM_KEY_STARTY			WINDOW_ITEM_Y + FINDER_KEYBOARD_KEY_OFFSET + 20
#define FINDER_KEYBOARD_CHAR_KEY_STARTY			FINDER_KEYBOARD_NUM_KEY_STARTY
#define FINDER_KEYBOARD_NUM_STARTX	 			FINDER_KEYBOARD_NUM_KEY_STARTX + 10
#define FINDER_KEYBOARD_CHAR_STARTX 			FINDER_KEYBOARD_CHAR_KEY_STARTX + 8
#define	FINDER_KEYBOARD_KEY_SIZE				MV_BMP[MVBMP_UNFOCUS_KEYPAD].bmWidth
#define	FINDER_KEYBOARD_BIGKEY_SIZE				56
#define FINDER_KEYBOARD_STR_STARTY				WINDOW_ITEM_Y + 10

CSAPP_Applet_t	CSApp_Video_Set(void);
void MV_Draw_Audio_Bar(HDC hdc);
void MV_Draw_Video_SetMenuBar(HDC hdc, U8 u8Focuskind, U8 esItem);
void MV_Draw_Video_SetSelectBar(HDC hdc, int y_gap, U8 esItem);
void MV_Video_Set_SetWindow(HDC hdc);

#endif
