/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
/* acconfig.h
   This file is in the public domain.

   Descriptive text for the C preprocessor macros that
   the distributed Autoconf macros can define.
   No software package will use all of them; autoheader copies the ones
   your configure.in uses into your configuration header file templates.

   The entries are in sort -df order: alphabetical, case insensitive,
   ignoring punctuation (such as underscores).  Although this order
   can split up related entries, it makes it easier to check whether
   a given entry is in the file.

   Leave the following blank line there!!  Autoheader needs it.  */


/* Define if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* #undef _ALL_SOURCE */
#endif

/* Define if using alloca.c.  */
/* #undef C_ALLOCA */

/* Define if type char is unsigned and you are not using gcc.  */
#ifndef __CHAR_UNSIGNED__
/* #undef __CHAR_UNSIGNED__ */
#endif

/* Define if the closedir function returns void instead of int.  */
/* #undef CLOSEDIR_VOID */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define to one of _getb67, GETB67, getb67 for Cray-2 and Cray-YMP systems.
   This function is required for alloca.c support on those systems.  */
/* #undef CRAY_STACKSEG_END */

/* Define for DGUX with <sys/dg_sys_info.h>.  */
/* #undef DGUX */

/* Define if you have <dirent.h>.  */
/* #undef DIRENT */

/* Define to the type of elements in the array set by `getgroups'.
   Usually this is either `int' or `gid_t'.  */
/* #undef GETGROUPS_T */

/* Define if the `getloadavg' function needs to be run setuid or setgid.  */
/* #undef GETLOADAVG_PRIVILEGED */

/* Define if the `getpgrp' function takes no argument.  */
/* #undef GETPGRP_VOID */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef gid_t */

/* Define if you have alloca, as a function or macro.  */
#define HAVE_ALLOCA 1

/* Define if you have <alloca.h> and it should be used (not on Ultrix).  */
#define HAVE_ALLOCA_H 1

/* Define if you don't have vprintf but do have _doprnt.  */
/* #undef HAVE_DOPRNT */

/* Define if your system has a working fnmatch function.  */
/* #undef HAVE_FNMATCH */

/* Define if your system has its own `getloadavg' function.  */
/* #undef HAVE_GETLOADAVG */

/* Define if you have the getmntent function.  */
/* #undef HAVE_GETMNTENT */

/* Define if the `long double' type works.  */
/* #undef HAVE_LONG_DOUBLE */

/* Define if you support file names longer than 14 characters.  */
/* #undef HAVE_LONG_FILE_NAMES */

/* Define if you have a working `mmap' system call.  */
/* #undef HAVE_MMAP */

/* Define if system calls automatically restart after interruption
   by a signal.  */
/* #undef HAVE_RESTARTABLE_SYSCALLS */

/* Define if your struct stat has st_blksize.  */
/* #undef HAVE_ST_BLKSIZE */

/* Define if your struct stat has st_blocks.  */
/* #undef HAVE_ST_BLOCKS */

/* Define if you have the strcoll function and it is properly defined.  */
/* #undef HAVE_STRCOLL */

/* Define if your struct stat has st_rdev.  */
/* #undef HAVE_ST_RDEV */

/* Define if you have the strftime function.  */
/* #undef HAVE_STRFTIME */

/* Define if you have the ANSI # stringizing operator in cpp. */
/* #undef HAVE_STRINGIZE */

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
/* #undef HAVE_SYS_WAIT_H */

/* Define if your struct tm has tm_zone.  */
/* #undef HAVE_TM_ZONE */

/* Define if you don't have tm_zone but do have the external array
   tzname.  */
/* #undef HAVE_TZNAME */

/* Define if you have <unistd.h>.  */
#define HAVE_UNISTD_H 1

/* Define if utime(file, NULL) sets file's timestamp to the present.  */
/* #undef HAVE_UTIME_NULL */

/* Define if you have <vfork.h>.  */
/* #undef HAVE_VFORK_H */

/* Define if you have the vprintf function.  */
#define HAVE_VPRINTF 1

/* Define if you have the wait3 system call.  */
/* #undef HAVE_WAIT3 */

/* Define as __inline if that's what the C compiler calls it.  */
/* #undef inline */

/* Define if int is 16 bits instead of 32.  */
/* #undef INT_16_BITS */

/* Define if long int is 64 bits.  */
/* #undef LONG_64_BITS */

/* Define if major, minor, and makedev are declared in <mkdev.h>.  */
/* #undef MAJOR_IN_MKDEV */

/* Define if major, minor, and makedev are declared in <sysmacros.h>.  */
/* #undef MAJOR_IN_SYSMACROS */

/* Define if on MINIX.  */
/* #undef _MINIX */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef mode_t */

/* Define if you don't have <dirent.h>, but have <ndir.h>.  */
/* #undef NDIR */

/* Define if you have <memory.h>, and <string.h> doesn't declare the
   mem* functions.  */
/* #undef NEED_MEMORY_H */

/* Define if your struct nlist has an n_un member.  */
/* #undef NLIST_NAME_UNION */

/* Define if you have <nlist.h>.  */
/* #undef NLIST_STRUCT */

/* Define if your C compiler doesn't accept -c and -o together.  */
/* #undef NO_MINUS_C_MINUS_O */

/* Define if your Fortran 77 compiler doesn't accept -c and -o together. */
/* #undef F77_NO_MINUS_C_MINUS_O */

/* Define to `long' if <sys/types.h> doesn't define.  */
/* #undef off_t */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define if the system does not provide POSIX.1 features except
   with this defined.  */
/* #undef _POSIX_1_SOURCE */

/* Define if you need to in order for stat and other things to work.  */
/* #undef _POSIX_SOURCE */

/* Define as the return type of signal handlers (int or void).  */
/* #undef RETSIGTYPE */

/* Define to the type of arg1 for select(). */
/* #undef SELECT_TYPE_ARG1 */

/* Define to the type of args 2, 3 and 4 for select(). */
/* #undef SELECT_TYPE_ARG234 */

/* Define to the type of arg5 for select(). */
/* #undef SELECT_TYPE_ARG5 */

/* Define if the `setpgrp' function takes no argument.  */
/* #undef SETPGRP_VOID */

/* Define if the setvbuf function takes the buffering type as its second
   argument and the buffer pointer as the third, as on System V
   before release 3.  */
/* #undef SETVBUF_REVERSED */

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown
 */
/* #undef STACK_DIRECTION */

/* Define if the `S_IS*' macros in <sys/stat.h> do not work properly.  */
/* #undef STAT_MACROS_BROKEN */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define on System V Release 4.  */
/* #undef SVR4 */

/* Define if you don't have <dirent.h>, but have <sys/dir.h>.  */
/* #undef SYSDIR */

/* Define if you don't have <dirent.h>, but have <sys/ndir.h>.  */
/* #undef SYSNDIR */

/* Define if `sys_siglist' is declared by <signal.h>.  */
/* #undef SYS_SIGLIST_DECLARED */

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef uid_t */

/* Define for Encore UMAX.  */
/* #undef UMAX */

/* Define for Encore UMAX 4.3 that has <inq_status/cpustats.h>
   instead of <sys/cpustats.h>.  */
/* #undef UMAX4_3 */

/* Define if you do not have <strings.h>, index, bzero, etc..  */
/* #undef USG */

/* Define vfork as fork if vfork does not work.  */
/* #undef vfork */

/* Define if the closedir function returns void instead of int.  */
/* #undef VOID_CLOSEDIR */

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* Define if the X Window System is missing or not being used.  */
/* #undef X_DISPLAY_MISSING */

/* Define if lex declares yytext as a char * by default, not a char[].  */
/* #undef YYTEXT_POINTER */

/* Version of MiniGUI */
#define MINIGUI_MAJOR_VERSION 1
#define MINIGUI_MINOR_VERSION 3
#define MINIGUI_MICRO_VERSION 3
#define MINIGUI_INTERFACE_AGE 0
#define MINIGUI_BINARY_AGE 0

/* Define if build lite version of MiniGUI */
/* #undef _LITE_VERSION */

/* Define if build stand-alone version of MiniGUI-Lite */
/* #undef _STAND_ALONE */

/* Define if build MiniGUI for no file I/O system */
#define _INCORE_RES 1

/* Define if use debug version of MiniGUI */
#define _DEBUG 1

/* Define if use coordinate transformation */
/* #undef _COOR_TRANS */

/* Define to 0 if use clockwise rotation of screen, otherwise to 1 */
/* #undef _ROT_DIR_CCW */

/* Define if use new GAL interfaces */
#define _USE_NEWGAL 1

/* Define if include fixed math routines */
#define _FIXED_MATH 1

/* Define if trace message dispatching of MiniGUI */
/* #undef _TRACE_MSG */

/* Define if the unit of timer is 10ms */
#define _TIMER_UNIT_10MS 1

/* Define if we can move window by mouse */
#define _MOVE_WINDOW_BY_MOUSE 1

/* Define if use flat window style */
/* #undef _FLAT_WINDOW_STYLE */

/* Define if mouse button can do double click */
#define _DOUBLE_CLICK 1

/* Define if include messages' string names */
/* #undef _MSG_STRING */

/* Define if is gray screen */
/* #undef _GRAY_SCREEN */

/* Define if is tiny size screen */
/* #undef _TINY_SCREEN */

/* Define if include VGA 16-color graphics engine */
/* #undef _VGA16_GAL */

/* Define if include SVGALib engine */
/* #undef _SVGALIB */

/* Define if include LibGGI engine */
/* #undef _LIBGGI */

/* Define if include EP7211 input engine */
/* #undef _EP7211_IAL */

/* Define if include ADS input engine */
/* #undef _ADS_IAL */

/* Define if include iPAQ input engine */
/* #undef _IPAQ_IAL */

/* Define if include mpc823 input engine */
/* #undef _MPC823_IAL */

/* Define if include px255b input engine */
/* #undef _PX255B_IAL */

/* Define if include iPAQ input engine */
/* #undef _THOR_IAL */

/* Define if include NEC VR4181 input engine */
/* #undef _VR4181_IAL */

/* Define if include IAL engine for Helio Touch Panel */
/* #undef _HELIO_IAL */

/* Define if include IAL engine for Tongfang STB */
/* #undef _TFSTB_IAL */

/* Define if include IAL engine for MT T800 */
/* #undef _T800_IAL */

/* Define if include IAL engine for uClinux touch screen palm/mc68ez328 */
/* #undef _MC68X328_IAL */

/* Define if include IAL engine for smdk2410 touch screen */
/* #undef _SMDK2410_IAL */


/* Define if include the dummy IAL engine */
#define _DUMMY_IAL 1

/* Define if include the QVFB IAL engine */
#define _QVFB_IAL 1

/* Define if include native graphics engine */
/* #undef _NATIVE_GAL_ENGINE */

/* Define if support native graphics engine on FBCON */
#define _NATIVE_GAL_FBCON 1

/* Define if support native graphics engine on QVFB */
#define _NATIVE_GAL_QVFB 1

/* Define if support native graphics engine on eCos LCD */
/* #undef _NATIVE_GAL_ECOSLCD */

/* Define if include 1BPP FB subdriver (MSB is right) */
/* #undef _FBLIN1R_SUPPORT */

/* Define if include 1BPP FB subdriver (MSB is left) */
/* #undef _FBLIN1L_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is right) */
/* #undef _FBLIN2R_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is left) */
/* #undef _FBLIN2L_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is right) */
/* #undef _FBLIN4R_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is left) */
/* #undef _FBLIN4L_SUPPORT */

/* Define if include 8BPP FB subdriver */
/* #undef _FBLIN8_SUPPORT */

/* Define if include 26BPP FB subdriver */
/* #undef _FBLIN16_SUPPORT */

/* Define if include 24BPP FB subdriver */
/* #undef _FBLIN24_SUPPORT */

/* Define if include 32BPP FB subdriver */
/* #undef _FBLIN32_SUPPORT */

/* Define if include VGA16 FB subdriver */
/* #undef _FBVGA16_SUPPORT */

/* Define if include native input engine */
#define _NATIVE_IAL_ENGINE 1

/* Define if include PS2 mouse subdriver */
#define _PS2_SUPPORT 1

/* Define if include IMPS2 mouse subdriver */
/* #undef _IMPS2_SUPPORT */

/* Define if include GPM mouse subdriver */
/* #undef _GPM_SUPPORT */

/* Define if include MS mouse subdriver */
/* #undef _MS_SUPPORT */

/* Define if include MS3 mouse subdriver */
/* #undef _MS3_SUPPORT */

/* Define if build pure FrameBuffer-based graphics engine */
/* #undef _PURE_FB_GFX */

/* Define if your Linux have text mode */
#define _HAVE_TEXT_MODE 1

/* Define if include cursor support */
/* #undef _CURSOR_SUPPORT */

/* Define if support raw bitmap fonts */
#define _RBF_SUPPORT 1

/* Define if include incore GB2312 12x12 RBF font */
#define _INCORERBF_GB12 1

/* Define if support var bitmap fonts */
#define _VBF_SUPPORT 1

/* Define if include in-core font: SansSerif */
#define _INCOREFONT_SANSSERIF 1

/* Define if include in-core font: Courier */
#define _INCOREFONT_COURIER 1

/* Define if include in-core font: Symbol */
#define _INCOREFONT_SYMBOL 1

/* Define if include in-core font: VGAS */
#define _INCOREFONT_VGAS 1

/* Define if support QPF font */
/* #undef _QPF_SUPPORT */

/* Define if support TrueType font based on FreeType 1.3 or FreeType 2 */
// #undef _TTF_SUPPORT
#define _TTF_SUPPORT 1

/* Define if has FreeType 2 */
/* #undef _HAS_FREETYPE2 */

/* Define if support Adobe Type1 */
/* #undef _TYPE1_SUPPORT */

/* Define if support Latin 2 charset */
/* #undef _LATIN2_SUPPORT */

/* Define if support Latin 3 charset */
/* #undef _LATIN3_SUPPORT */

/* Define if support Latin 4 charset */
/* #undef _LATIN4_SUPPORT */

/* Define if support Cyrillic charset */
/* #undef _CYRILLIC_SUPPORT */

/* Define if support Arabic charset */
/* #undef _ARABIC_SUPPORT */

/* Define if support Greek charset */
/* #undef _GREEK_SUPPORT */

/* Define if support Hebrew charset */
/* #undef _HEBREW_SUPPORT */

/* Define if support Latin 5 charset */
/* #undef _LATIN5_SUPPORT */

/* Define if support Latin 6 charset */
/* #undef _LATIN6_SUPPORT */

/* Define if support Thai charset */
/* #undef _THAI_SUPPORT */

/* Define if support Latin 7 charset */
/* #undef _LATIN7_SUPPORT */

/* Define if support Latin 8 charset */
/* #undef _LATIN8_SUPPORT */

/* Define if support Latin 9 charset */
#define _LATIN9_SUPPORT 1

/* Define if support Latin 10 charset */
/* #undef _LATIN10_SUPPORT */

/* Define if support GB2312 charset */
#define _GB_SUPPORT 1

/* Define if support GBK charset */
#define _GBK_SUPPORT 1

/* Define if support GB18030 charset */
/* #undef _GB18030_SUPPORT */

/* Define if support BIG5 charset */
#define _BIG5_SUPPORT 1

/* Define if support EUCKR charset */
/* #undef _EUCKR_SUPPORT */

/* Define if support EUCJP charset */
/* #undef _EUCJP_SUPPORT */

/* Define if support SHIFTJIS charset */
/* #undef _SHIFTJIS_SUPPORT */

/* Define if support UNICODE */
#define _UNICODE_SUPPORT 1

/* Define if use the default keyboard layout */
/* #undef _KBD_LAYOUT_DEFAULT */

/* Define if use the French PC keyboard layout */
#define _KBD_LAYOUT_FRPC 1

/* Define if use the French keyboard layout */
/* #undef _KBD_LAYOUT_FR */

/* Define if use the German keyboard layout */
/* #undef _KBD_LAYOUT_DE */

/* Define if use the German-Latin1 keyboard layout */
/* #undef _KBD_LAYOUT_DELATIN1 */

/* Define if use the Italian keyboard layout */
/* #undef _KBD_LAYOUT_IT */

/* Define if use the Spanish keyboard layout */
/* #undef _KBD_LAYOUT_ES */

/* Define if use the Spanish CP850 keyboard layout */
/* #undef _KBD_LAYOUT_ESCP850 */

/* Define if include SaveBitmap function */
#define _SAVE_BITMAP 1

/* Define if support PCX bmp file format */
/* #undef _PCX_FILE_SUPPORT */

/* Define if support LBM bmp file format */
/* #undef _LBM_FILE_SUPPORT */

/* Define if support TGA bmp file format */
/* #undef _TGA_FILE_SUPPORT */

/* Define if support GIF bmp file format */
#define _GIF_FILE_SUPPORT 1

/* Define if support JPG bmp file format */
/* #undef _JPG_FILE_SUPPORT */

/* Define if support PNG bmp file format */
/* #undef _PNG_FILE_SUPPORT */

/* Define if provide GB2312 IME */
/* #undef _IME_GB2312 */

/* Define if provide GB2312 Intelligent Pinyin IME module */
/* #undef _IME_GB2312_PINYIN */

/* Define if include About Dialog Box */
/* #undef _MISC_ABOUTDLG */

/* Define if include code for screenshots */
#define _MISC_SAVESCREEN 1

/* Define if include STATIC control */
#define _CTRL_STATIC 1

/* Define if include BUTTON control */
#define _CTRL_BUTTON 1

/* Define if include SIMEDIT control */
#define _CTRL_SIMEDIT 1

/* Define if include SLEDIT control */
#define _CTRL_SLEDIT 1

/* Define if include MLEDIT control */
#define _CTRL_MLEDIT 1

/* Define if include LISTBOX control */
#define _CTRL_LISTBOX 1

/* Define if include PROGRESSBAR control */
#define _CTRL_PROGRESSBAR 1

/* Define if include TOOLBAR control */
#define _CTRL_TOOLBAR 1

/* Define if include NEWTOOLBAR control */
#define _CTRL_NEWTOOLBAR 1

/* Define if include MENUBUTTON control */
#define _CTRL_MENUBUTTON 1

/* Define if include TRACKBAR control */
#define _CTRL_TRACKBAR 1

/* Define if include COMBOBOX control */
#define _CTRL_COMBOBOX 1

/* Define if include PROPSHEETcontrol */
#define _CTRL_PROPSHEET 1

/* Define if include MONTHCALENDAR control */
#define _EXT_CTRL_MONTHCAL 1

/* Define if include TREEVIEW control */
#define _EXT_CTRL_TREEVIEW 1

/* Define if include SPINBOX control */
#define _EXT_CTRL_SPINBOX 1

/* Define if include COOLBAR control */
#define _EXT_CTRL_COOLBAR 1

/* Define if include LISTVIEW control */
#define _EXT_CTRL_LISTVIEW 1

/* Define if include GRID control */
#define _EXT_CTRL_GRID 1

/* Define if include full gif support */
#define _EXT_FULLGIF 1

/* Define if include skin support */
#define _EXT_SKIN 1

/* Define if include vcongui support */
#define _LIB_VCONGUI 1


/* Leave that blank line there!!  Autoheader needs it.
   If you're adding to this file, keep in mind:
   The entries are in sort -df order: alphabetical, case insensitive,
   ignoring punctuation (such as underscores).  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have the `alloca' function. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
/* #undef HAVE_MMAP */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <termio.h> header file. */
#define HAVE_TERMIO_H 1

/* Define to 1 if you have the `tmpfile' function. */
#define HAVE_TMPFILE 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at runtime.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef size_t */
