/*
  Automatically generated by 'make config' -- don't edit!
*/
#define LINUX "/home/xm.chen/work/linuxdrv/linux-kernel-2.6"
#define PREFIX ""
#define KCC "arm-linux-gcc"
#define UCC "arm-linux-gcc"
#define LD "arm-linux-ld"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#define USE_PM 1
#define UNSAFE_TOOLS 1
#undef  CONFIG_CARDBUS
#undef  CONFIG_PNP_BIOS
#define UTS_RELEASE "2.6.12.5"
#define UTS_VERSION "#244 Thu Feb 28 15:06:49 CST 2008"
#define LINUX_VERSION_CODE 132620
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#define MODDIR "/lib/modules/2.6.12.5"

/* Options from /home/xm.chen/work/linuxdrv/linux-kernel-2.6/.config */
#define CONFIG_MODULES 1
#define CONFIG_PCMCIA 1
#undef  CONFIG_SMP
#undef  CONFIG_PREEMPT
#undef  CONFIG_RTHAL
#undef  CONFIG_HIGHMEM
#undef  CONFIG_PCI
#undef  CONFIG_PM
#define CONFIG_SCSI 1
#undef  CONFIG_IEEE1394
#define CONFIG_INET 1
#undef  CONFIG_NET_PCMCIA_RADIO
#undef  CONFIG_TR
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_MODVERSIONS
#undef  CONFIG_DEBUG_KERNEL
#define CONFIG_PROC_FS 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#define ARCH "arm"
#define HOST_ARCH "i386"
#define AFLAGS ""
#undef  CONFIG_ISA
#define CONFIG_UID16 1

#define HAS_PROC_BUS 1
#define SYSV_INIT 1
#define RC_DIR "/etc/rc.d"
#define HAS_WORDEXP 1
#define MANDIR "/usr/share/man/"
#define XMANDIR "/usr/share/man/"
