#ifndef __KEY_CODES_H__
#define __KEY_CODES_H__

#include "common.h"

#include "merihkey.h"


#ifdef _MERIH_UART1_IAL

#define FRONT_KEY_NUMBER       0x80

#define MAX_FB_COMM_LENGTH    30
#define MIN_FB_COMMAND_LENGT  2    /* Command + Length*/
#define MAX_FB_RECV_LENGTH    10
#define FRONT_START_CODE                 0xF0
#define FRONT_RCU_KEY                    0x10
#define FRONT_RCU_REPEAT                 0x11
#define FRONT_FRONT_KEY                  0x12
#define FRONT_FRONT_REPEAT               0x13
#define FRONT_END_CODE                   0x0F
#define FRONT_KEY_COMMAND_HIGH_MASK      0xF0 /* For Front Communication by kb : 20110201 */

#define RCKEY_DEF_VAL          CSAPP_KEY_NULL

/****************************************************************
 *                       Type define                            *
 ****************************************************************/
typedef struct KeyScan_s
{
	unsigned char ScanCode;      /* RCU Scan Code */
	unsigned char KeyValue;       
} KeyScan_t;


typedef struct Keymap_s         /* Define a new structure type called Keymap */
{
	unsigned      KeyNumber;
	unsigned char CompanyCode[2];      /* the company code*/
	KeyScan_t     KeyScanCode[MAX_USER_KEY];       
} KeyMaps_t;                     /*Create a new keymap structure called DefaultKeys*/

typedef struct KeyCode_s         /* Define a new structure type For Key Code */
{
	struct KeyCode_s    *Next;
	unsigned char CompanyCode[2];      /* the company code*/
	unsigned char KeyCode[SCANCODE_USER];       
} KeyCode_t;

/****************************************************************
 *                      Global Variable                         *
 ****************************************************************/
KeyCode_t *FirstKeyCode;

KeyMaps_t X3TurboKey =
{
	55,
	{0x80, 0xBF},
	{
		{0x3B, CSAPP_KEY_POWER},    // 0
		{0x9B, CSAPP_KEY_TVRADIO},  // 1
		{0xC1, CSAPP_KEY_SD_HD},   	// 2
		{0xE1, CSAPP_KEY_0},   		// 3
		{0x49, CSAPP_KEY_1},   		// 4
		{0xC9, CSAPP_KEY_2},   		// 5
		{0x33, CSAPP_KEY_3},   		// 6
		{0x71, CSAPP_KEY_4},   		// 7
		{0xF1, CSAPP_KEY_5},   		// 8
		{0x13, CSAPP_KEY_6},   		// 9
		{0x51, CSAPP_KEY_7},   		// 10
		{0xD1, CSAPP_KEY_8},   		// 11
		{0x23, CSAPP_KEY_9},   		// 12
		{0x41, CSAPP_KEY_RECALL},   // 13
		{0x39, CSAPP_KEY_MUTE},   	// 14
		{0x69, CSAPP_KEY_RED},   	// 15
		{0x43, CSAPP_KEY_GREEN},	// 16
		{0xC3, CSAPP_KEY_YELLOW},   // 17
		{0x21, CSAPP_KEY_BLUE},   	// 18
		{0xA9, CSAPP_KEY_MENU},   	// 19
		{0x6B, CSAPP_KEY_EPG},   	// 20
		{0x0B, CSAPP_KEY_INFO},   	// 21
		{0xBB, CSAPP_KEY_PG_UP},    // 22
		{0x31, CSAPP_KEY_PG_DOWN},  // 23
		{0x53, CSAPP_KEY_UP},   	// 24
		{0x4B, CSAPP_KEY_DOWN},   	// 25
		{0x99, CSAPP_KEY_LEFT},   	// 26
		{0x83, CSAPP_KEY_RIGHT},   	// 27
		{0x73, CSAPP_KEY_OK},   	// 28
		{0x81, CSAPP_KEY_VOL_UP},   // 29
		{0xA1, CSAPP_KEY_VOL_DOWN}, // 30
		{0xA3, CSAPP_KEY_EXIT},   	// 31
		{0xB1, CSAPP_KEY_CH_UP},	// 32
		{0x79, CSAPP_KEY_CH_DOWN},  // 33
		{0xD9, CSAPP_KEY_F1},   	// 34
		{0x59, CSAPP_KEY_F2},   	// 35
		{0x91, CSAPP_KEY_SAT},   	// 36
		{0x5B, CSAPP_KEY_TV_AV},   	// 37
		{0x11, CSAPP_KEY_FAVOLIST}, // 38
		{0x01, CSAPP_KEY_REC},   	// 39
		{0x1B, CSAPP_KEY_PLAY},   	// 40
		{0x8B, CSAPP_KEY_LIST},   	// 41
		{0x2B, CSAPP_KEY_STOP},   	// 42
		{0xE3, CSAPP_KEY_PAUSE},  	// 43
		{0xB3, CSAPP_KEY_SLEEP},   	// 44
		{0x63, CSAPP_KEY_REW},   	// 45
		{0xAB, CSAPP_KEY_FF},   	// 46
		{0x61, CSAPP_KEY_SLOW_B},   // 47
		{0x09, CSAPP_KEY_SLOW},  	// 48
		{0x69, CSAPP_KEY_FIND},   	// 49
		{0x43, CSAPP_KEY_V_MODE},   // 50
		{0xC3, CSAPP_KEY_TEXT},   	// 51
		{0x21, CSAPP_KEY_AUDIO},   	// 52
		{0xD9, CSAPP_KEY_NET_CFG}, 	// 53
		{0x59, CSAPP_KEY_ZOOM},   	// 54
	}
};

KeyMaps_t ChipBoxRcu =
{
	54,
	{0x40, 0x9F},
	{
		{0x50, CSAPP_KEY_POWER},    // 0
		{0x58, CSAPP_KEY_TVRADIO},  // 1
		{0x08, CSAPP_KEY_0},   		// 2
		{0x88, CSAPP_KEY_1},   		// 3
		{0x48, CSAPP_KEY_2},   		// 4
		{0xC8, CSAPP_KEY_3},   		// 5
		{0x28, CSAPP_KEY_4},   		// 6
		{0xA8, CSAPP_KEY_5},   		// 7
		{0x68, CSAPP_KEY_6},   		// 8
		{0xE8, CSAPP_KEY_7},   		// 9
		{0x18, CSAPP_KEY_8},   		// 10
		{0x98, CSAPP_KEY_9},   		// 11
		{0x82, CSAPP_KEY_RECALL},   // 12
		{0x30, CSAPP_KEY_MUTE},   	// 13
		{0xD2, CSAPP_KEY_RED},   	// 14
		{0x52, CSAPP_KEY_GREEN},	// 15
		{0x92, CSAPP_KEY_YELLOW},   // 16
		{0x12, CSAPP_KEY_BLUE},   	// 17
		{0x20, CSAPP_KEY_MENU},   	// 18
		{0x10, CSAPP_KEY_EPG},   	// 19
		{0x60, CSAPP_KEY_INFO},   	// 20
		{0x90, CSAPP_KEY_PG_UP},    // 21
		{0xA0, CSAPP_KEY_PG_DOWN},  // 22
		{0x00, CSAPP_KEY_UP},   	// 23
		{0x80, CSAPP_KEY_DOWN},   	// 24
		{0xC0, CSAPP_KEY_LEFT},   	// 25
		{0x40, CSAPP_KEY_RIGHT},   	// 26
		{0xF8, CSAPP_KEY_OK},   	// 27
		{0x22, CSAPP_KEY_VOL_UP},   // 28
		{0xC2, CSAPP_KEY_VOL_DOWN}, // 39
		{0x38, CSAPP_KEY_EXIT},   	// 30
		// {0x44, CSAPP_KEY_CH_UP},	// 31
		// {0x64, CSAPP_KEY_CH_DOWN},  // 32
		{0xEA, CSAPP_KEY_F1},   	// 31
		{0x6A, CSAPP_KEY_F2},   	// 32
		{0xAA, CSAPP_KEY_F3},   	// 33
		{0x2A, CSAPP_KEY_F4},   	// 34
		{0x78, CSAPP_KEY_SAT},   	// 35
		{0xB8, CSAPP_KEY_TV_AV},   	// 36
		{0xD8, CSAPP_KEY_FAVOLIST}, // 37
		{0x3A, CSAPP_KEY_REC},   	// 38
		{0xB0, CSAPP_KEY_PLAY},   	// 39
		{0x0A, CSAPP_KEY_LIST},   	// 40
		{0xD0, CSAPP_KEY_STOP},   	// 41
		{0x1A, CSAPP_KEY_PAUSE},  	// 42
		{0x32, CSAPP_KEY_SLEEP},   	// 43
		{0x02, CSAPP_KEY_REW},   	// 44
		{0xE0, CSAPP_KEY_FF},   	// 45
		{0xAA, CSAPP_KEY_SLOW_B},   // 46 F3
		{0x2A, CSAPP_KEY_SLOW},  	// 47 F4
		{0xD2, CSAPP_KEY_FIND},   	// 48
		{0x52, CSAPP_KEY_V_MODE},   // 49
		{0x92, CSAPP_KEY_TEXT},   	// 50
		{0x12, CSAPP_KEY_AUDIO},   	// 51
		{0xEA, CSAPP_KEY_NET_CFG}, 	// 52 F1
		{0x6A, CSAPP_KEY_ZOOM},   	// 53 F2
	}
};

KeyMaps_t CelestialKey =
{
	37,
	{0x00, 0xFF},
	{
		{0x98, CSAPP_KEY_POWER},    // 0
		{0x10, CSAPP_KEY_TVRADIO},	// 1
		{0x32, CSAPP_KEY_0},		// 2
		{0x4A, CSAPP_KEY_1},		// 3
		{0x0A, CSAPP_KEY_2},		// 4
		{0x08, CSAPP_KEY_3},		// 5
		{0xC8, CSAPP_KEY_4},		// 6
		{0x6A, CSAPP_KEY_5},		// 7
		{0x2A, CSAPP_KEY_6},		// 8
		{0x28, CSAPP_KEY_7},		// 9
		{0xE8, CSAPP_KEY_8},		// 10
		{0x72, CSAPP_KEY_9},		// 11
		{0xF0, CSAPP_KEY_RECALL},	// 12
		{0x9A, CSAPP_KEY_MUTE},		// 13
		{0x30, CSAPP_KEY_FIND},		// 14
		{0xA2, CSAPP_KEY_RED},		// 15
		{0xA0, CSAPP_KEY_GREEN},	// 16
		{0xAA, CSAPP_KEY_YELLOW},	// 17
		{0xA8, CSAPP_KEY_BLUE},		// 18
		{0xB2, CSAPP_KEY_MENU},		// 19
		{0xB0, CSAPP_KEY_EXIT},		// 20
		{0x52, CSAPP_KEY_EPG},		// 21
		{0x12, CSAPP_KEY_INFO},		// 22
		{0x48, CSAPP_KEY_PG_DOWN},	// 23
		{0x70, CSAPP_KEY_PG_UP},	// 24
		{0x60, CSAPP_KEY_UP},		// 25
		{0x68, CSAPP_KEY_DOWN},		// 26
		{0x5A, CSAPP_KEY_LEFT},		// 27
		{0xD8, CSAPP_KEY_RIGHT},	// 28
		{0x58, CSAPP_KEY_OK},		// 29
		{0x88, CSAPP_KEY_SAT},		// 30
		{0x8A, CSAPP_KEY_FAVOLIST},	// 31
		{0xD0, CSAPP_KEY_SUBTITLE},	// 32
		{0xA2, CSAPP_KEY_LANG},		// 33
		{0xA0, CSAPP_KEY_AUDIO},	// 34
		{0xAA, CSAPP_KEY_PAUSE},	// 35
		{0xA8, CSAPP_KEY_TEXT},		// 36
	}
};

unsigned char FrontKeyCode [FRONT_KEY_NUMBER] =
{
	RCKEY_DEF_VAL, 		/* 0x00 */
	RCKEY_DEF_VAL, 		/* 0x01 */
	RCKEY_DEF_VAL, 		/* 0x02 */
	RCKEY_DEF_VAL, 		/* 0x03 */
	RCKEY_DEF_VAL, 		/* 0x04 */
	RCKEY_DEF_VAL, 		/* 0x05 */
	RCKEY_DEF_VAL, 		/* 0x06 */
	RCKEY_DEF_VAL, 		/* 0x07 */
	RCKEY_DEF_VAL, 		/* 0x08 */
	RCKEY_DEF_VAL, 		/* 0x09 */
	RCKEY_DEF_VAL, 		/* 0x0a */
	RCKEY_DEF_VAL, 		/* 0x0b */
	RCKEY_DEF_VAL, 		/* 0x0c */
	RCKEY_DEF_VAL, 		/* 0x0d */
	RCKEY_DEF_VAL, 		/* 0x0e */
	CSAPP_KEY_HOLD, 	/* 0x0f */
	CSAPP_KEY_POWER, 	/* 0x10 */
	RCKEY_DEF_VAL, 		/* 0x11 */
	RCKEY_DEF_VAL, 		/* 0x12 */
	RCKEY_DEF_VAL, 		/* 0x13 */
	RCKEY_DEF_VAL, 		/* 0x14 */
	RCKEY_DEF_VAL, 		/* 0x15 */
	RCKEY_DEF_VAL, 		/* 0x16 */
	RCKEY_DEF_VAL, 		/* 0x17 */
	RCKEY_DEF_VAL, 		/* 0x18 */
	RCKEY_DEF_VAL, 		/* 0x19 */
	RCKEY_DEF_VAL, 		/* 0x1a */
	RCKEY_DEF_VAL, 		/* 0x1b */
	RCKEY_DEF_VAL, 		/* 0x1c */
	RCKEY_DEF_VAL, 		/* 0x1d */
	RCKEY_DEF_VAL, 		/* 0x1e */
	CSAPP_KEY_DOWN, 	/* 0x1f */
	RCKEY_DEF_VAL, 		/* 0x20 */
	RCKEY_DEF_VAL, 		/* 0x21 */
	RCKEY_DEF_VAL, 		/* 0x22 */
	RCKEY_DEF_VAL, 		/* 0x23 */
	RCKEY_DEF_VAL, 		/* 0x24 */
	RCKEY_DEF_VAL, 		/* 0x25 */
	RCKEY_DEF_VAL, 		/* 0x26 */
	RCKEY_DEF_VAL, 		/* 0x27 */
	RCKEY_DEF_VAL, 		/* 0x28 */
	RCKEY_DEF_VAL, 		/* 0x29 */
	RCKEY_DEF_VAL, 		/* 0x2a */
	RCKEY_DEF_VAL, 		/* 0x2b */
	RCKEY_DEF_VAL, 		/* 0x2c */
	RCKEY_DEF_VAL, 		/* 0x2d */
	RCKEY_DEF_VAL, 		/* 0x2e */
	CSAPP_KEY_UP, 		/* 0x2f */
	RCKEY_DEF_VAL, 		/* 0x30 */
	RCKEY_DEF_VAL, 		/* 0x31 */
	RCKEY_DEF_VAL, 		/* 0x32 */
	CSAPP_KEY_UPDATE, 	/* 0x33 */
	RCKEY_DEF_VAL, 		/* 0x34 */
	RCKEY_DEF_VAL, 		/* 0x35 */
	RCKEY_DEF_VAL, 		/* 0x36 */
	CSAPP_KEY_RIGHT, 	/* 0x37 */
	RCKEY_DEF_VAL, 		/* 0x38 */
	RCKEY_DEF_VAL, 		/* 0x39 */
	RCKEY_DEF_VAL, 		/* 0x3a */
	CSAPP_KEY_LEFT,		/* 0x3b */
	CSAPP_KEY_DIAG, 	/* 0x3c */
	CSAPP_KEY_OK, 		/* 0x3d */
	CSAPP_KEY_MENU, 	/* 0x3e */
	RCKEY_DEF_VAL, 		/* 0x3f */
	RCKEY_DEF_VAL, 		/* 0x40 */
	RCKEY_DEF_VAL, 		/* 0x41 */
	RCKEY_DEF_VAL, 		/* 0x42 */
	RCKEY_DEF_VAL, 		/* 0x43 */
	RCKEY_DEF_VAL, 		/* 0x44 */
	RCKEY_DEF_VAL, 		/* 0x45 */
	RCKEY_DEF_VAL, 		/* 0x46 */
	RCKEY_DEF_VAL, 		/* 0x47 */
	RCKEY_DEF_VAL, 		/* 0x48 */
	RCKEY_DEF_VAL, 		/* 0x49 */
	RCKEY_DEF_VAL, 		/* 0x4a */
	RCKEY_DEF_VAL, 		/* 0x4b */
	RCKEY_DEF_VAL, 		/* 0x4c */
	RCKEY_DEF_VAL, 		/* 0x4d */
	RCKEY_DEF_VAL, 		/* 0x4e */
	RCKEY_DEF_VAL, 		/* 0x4f */
	RCKEY_DEF_VAL, 		/* 0x50 */
	RCKEY_DEF_VAL, 		/* 0x51 */
	RCKEY_DEF_VAL, 		/* 0x52 */
	RCKEY_DEF_VAL, 		/* 0x53 */
	RCKEY_DEF_VAL, 		/* 0x54 */
	RCKEY_DEF_VAL, 		/* 0x55 */
	RCKEY_DEF_VAL, 		/* 0x56 */
	RCKEY_DEF_VAL, 		/* 0x57 */
	RCKEY_DEF_VAL, 		/* 0x58 */
	RCKEY_DEF_VAL, 		/* 0x59 */
	RCKEY_DEF_VAL, 		/* 0x5a */
	RCKEY_DEF_VAL, 		/* 0x5b */
	RCKEY_DEF_VAL, 		/* 0x5c */
	RCKEY_DEF_VAL, 		/* 0x5d */
	RCKEY_DEF_VAL, 		/* 0x5e */
	RCKEY_DEF_VAL, 		/* 0x5f */
	RCKEY_DEF_VAL, 		/* 0x60 */
	RCKEY_DEF_VAL, 		/* 0x61 */
	RCKEY_DEF_VAL, 		/* 0x62 */
	RCKEY_DEF_VAL, 		/* 0x63 */
	RCKEY_DEF_VAL, 		/* 0x64 */
	RCKEY_DEF_VAL, 		/* 0x65 */
	RCKEY_DEF_VAL, 		/* 0x66 */
	RCKEY_DEF_VAL, 		/* 0x67 */
	RCKEY_DEF_VAL, 		/* 0x68 */
	RCKEY_DEF_VAL, 		/* 0x69 */
	RCKEY_DEF_VAL, 		/* 0x6a */
	RCKEY_DEF_VAL, 		/* 0x6b */
	RCKEY_DEF_VAL, 		/* 0x6c */
	RCKEY_DEF_VAL, 		/* 0x6d */
	RCKEY_DEF_VAL, 		/* 0x6e */
	RCKEY_DEF_VAL, 		/* 0x6f */
	CSAPP_KEY_POWER, 	/* 0x70 */
	RCKEY_DEF_VAL, 		/* 0x71 */
	RCKEY_DEF_VAL, 		/* 0x72 */
	RCKEY_DEF_VAL, 		/* 0x73 */
	RCKEY_DEF_VAL, 		/* 0x74 */
	RCKEY_DEF_VAL, 		/* 0x75 */
	RCKEY_DEF_VAL, 		/* 0x76 */
	RCKEY_DEF_VAL, 		/* 0x77 */
	RCKEY_DEF_VAL, 		/* 0x78 */
	RCKEY_DEF_VAL, 		/* 0x79 */
	RCKEY_DEF_VAL, 		/* 0x7a */
	RCKEY_DEF_VAL, 		/* 0x7b */
	RCKEY_DEF_VAL, 		/* 0x7c */
	RCKEY_DEF_VAL, 		/* 0x7d */
	RCKEY_DEF_VAL, 		/* 0x7e */
	CSAPP_KEY_EXIT 		/* 0x7f */
};

#else //#ifdef _MERIH_UART1_IAL

#define RCKEY_DEF_VAL		SCANCODE_SPACE

#if 0
int basic_keycodes[] = {
	RCKEY_DEF_VAL, 		/* 0x00 */
	RCKEY_DEF_VAL, 		/* 0x01 */
	RCKEY_DEF_VAL, 		/* 0x02 */
	RCKEY_DEF_VAL, 		/* 0x03 */
	RCKEY_DEF_VAL, 		/* 0x04 */
	SCANCODE_H, 		/* 0x05 */
	SCANCODE_CURSORUP, 	/* 0x06 */
	RCKEY_DEF_VAL, 		/* 0x07 */
	SCANCODE_O, 		/* 0x08 */
	RCKEY_DEF_VAL, 		/* 0x09 */
	RCKEY_DEF_VAL, 		/* 0x0a */
	SCANCODE_P, 		/* 0x0b */
	SCANCODE_K, 		/* 0x0c */
	SCANCODE_ESCAPE, 	/* 0x0d */
	SCANCODE_C, 		/* 0x0e */
	SCANCODE_L, 		/* 0x0f */
	SCANCODE_3, 		/* 0x10 */
	SCANCODE_F, 		/* 0x11 */
	SCANCODE_E, 		/* 0x12 */
	SCANCODE_4, 		/* 0x13 */
	SCANCODE_7, 		/* 0x14 */
	SCANCODE_J, 		/* 0x15 */
	SCANCODE_CURSORDOWN, 	/* 0x16 */
	SCANCODE_8, 		/* 0x17 */
	RCKEY_DEF_VAL, 		/* 0x18 */
	SCANCODE_B, 		/* 0x19 */
	SCANCODE_ENTER, 	/* 0x1a */
	SCANCODE_CURSORRIGHT, 	/* 0x1b */
	RCKEY_DEF_VAL, 		/* 0x1c */
	RCKEY_DEF_VAL, 		/* 0x1d */
	RCKEY_DEF_VAL, 		/* 0x1e */
	RCKEY_DEF_VAL, 		/* 0x1f */
	RCKEY_DEF_VAL, 		/* 0x20 */
	RCKEY_DEF_VAL, 		/* 0x21 */
	RCKEY_DEF_VAL, 		/* 0x22 */
	RCKEY_DEF_VAL, 		/* 0x23 */
	RCKEY_DEF_VAL, 		/* 0x24 */
	RCKEY_DEF_VAL, 		/* 0x25 */
	RCKEY_DEF_VAL, 		/* 0x26 */
	RCKEY_DEF_VAL, 		/* 0x27 */
	RCKEY_DEF_VAL, 		/* 0x28 */
	RCKEY_DEF_VAL, 		/* 0x29 */
	RCKEY_DEF_VAL, 		/* 0x2a */
	RCKEY_DEF_VAL, 		/* 0x2b */
	RCKEY_DEF_VAL, 		/* 0x2c */
	RCKEY_DEF_VAL, 		/* 0x2d */
	RCKEY_DEF_VAL, 		/* 0x2e */
	RCKEY_DEF_VAL, 		/* 0x2f */
	RCKEY_DEF_VAL, 		/* 0x30 */
	RCKEY_DEF_VAL, 		/* 0x31 */
	RCKEY_DEF_VAL, 		/* 0x32 */
	RCKEY_DEF_VAL, 		/* 0x33 */
	RCKEY_DEF_VAL, 		/* 0x34 */
	RCKEY_DEF_VAL, 		/* 0x35 */
	RCKEY_DEF_VAL, 		/* 0x36 */
	RCKEY_DEF_VAL, 		/* 0x37 */
	RCKEY_DEF_VAL, 		/* 0x38 */
	RCKEY_DEF_VAL, 		/* 0x39 */
	RCKEY_DEF_VAL, 		/* 0x3a */
	RCKEY_DEF_VAL, 		/* 0x3b */
	RCKEY_DEF_VAL, 		/* 0x3c */
	RCKEY_DEF_VAL, 		/* 0x3d */
	RCKEY_DEF_VAL, 		/* 0x3e */
	RCKEY_DEF_VAL, 		/* 0x3f */
	RCKEY_DEF_VAL, 		/* 0x40 */
	RCKEY_DEF_VAL, 		/* 0x41 */
	RCKEY_DEF_VAL, 		/* 0x42 */
	RCKEY_DEF_VAL, 		/* 0x43 */
	RCKEY_DEF_VAL, 		/* 0x44 */
	SCANCODE_G, 		/* 0x45 */
	RCKEY_DEF_VAL, 		/* 0x46 */
	RCKEY_DEF_VAL, 		/* 0x47 */
	SCANCODE_N, 		/* 0x48 */
	RCKEY_DEF_VAL, 		/* 0x49 */
	SCANCODE_M, 		/* 0x4a */
	RCKEY_DEF_VAL, 		/* 0x4b */
	SCANCODE_0, 		/* 0x4c */
	SCANCODE_F1, 		/* 0x4d */
	SCANCODE_9, 		/* 0x4e */
	RCKEY_DEF_VAL, 		/* 0x4f */
	SCANCODE_2, 		/* 0x50 */
	SCANCODE_D, 		/* 0x51 */
	SCANCODE_1, 		/* 0x52 */
	RCKEY_DEF_VAL, 		/* 0x53 */
	SCANCODE_6, 		/* 0x54 */
	SCANCODE_I, 		/* 0x55 */
	SCANCODE_5, 		/* 0x56 */
	RCKEY_DEF_VAL, 		/* 0x57 */
	RCKEY_DEF_VAL, 		/* 0x58 */
	SCANCODE_A, 		/* 0x59 */
	SCANCODE_CURSORLEFT, 	/* 0x5a */
	RCKEY_DEF_VAL, 		/* 0x5b */
	RCKEY_DEF_VAL, 		/* 0x5c */
	RCKEY_DEF_VAL, 		/* 0x5d */
	RCKEY_DEF_VAL, 		/* 0x5e */
	RCKEY_DEF_VAL, 		/* 0x5f */
	RCKEY_DEF_VAL, 		/* 0x60 */
	RCKEY_DEF_VAL, 		/* 0x61 */
	RCKEY_DEF_VAL, 		/* 0x62 */
	RCKEY_DEF_VAL, 		/* 0x63 */
	RCKEY_DEF_VAL, 		/* 0x64 */
	RCKEY_DEF_VAL, 		/* 0x65 */
	RCKEY_DEF_VAL, 		/* 0x66 */
	RCKEY_DEF_VAL, 		/* 0x67 */
	RCKEY_DEF_VAL, 		/* 0x68 */
	RCKEY_DEF_VAL, 		/* 0x69 */
	RCKEY_DEF_VAL, 		/* 0x6a */
	RCKEY_DEF_VAL, 		/* 0x6b */
	RCKEY_DEF_VAL, 		/* 0x6c */
	RCKEY_DEF_VAL, 		/* 0x6d */
	RCKEY_DEF_VAL, 		/* 0x6e */
	RCKEY_DEF_VAL, 		/* 0x6f */
	RCKEY_DEF_VAL, 		/* 0x70 */
	RCKEY_DEF_VAL, 		/* 0x71 */
	RCKEY_DEF_VAL, 		/* 0x72 */
	RCKEY_DEF_VAL, 		/* 0x73 */
	RCKEY_DEF_VAL, 		/* 0x74 */
	RCKEY_DEF_VAL, 		/* 0x75 */
	RCKEY_DEF_VAL, 		/* 0x76 */
	RCKEY_DEF_VAL, 		/* 0x77 */
	RCKEY_DEF_VAL, 		/* 0x78 */
	RCKEY_DEF_VAL, 		/* 0x79 */
	RCKEY_DEF_VAL, 		/* 0x7a */
	RCKEY_DEF_VAL, 		/* 0x7b */
	RCKEY_DEF_VAL, 		/* 0x7c */
	RCKEY_DEF_VAL, 		/* 0x7d */
	RCKEY_DEF_VAL, 		/* 0x7e */
	RCKEY_DEF_VAL, 		/* 0x7f */
	RCKEY_DEF_VAL, 		/* 0x80 */
	RCKEY_DEF_VAL, 		/* 0x81 */
	RCKEY_DEF_VAL, 		/* 0x82 */
	RCKEY_DEF_VAL, 		/* 0x83 */
	RCKEY_DEF_VAL, 		/* 0x84 */
	RCKEY_DEF_VAL, 		/* 0x85 */
	RCKEY_DEF_VAL, 		/* 0x86 */
	RCKEY_DEF_VAL, 		/* 0x87 */
	RCKEY_DEF_VAL, 		/* 0x88 */
	RCKEY_DEF_VAL, 		/* 0x89 */
	RCKEY_DEF_VAL, 		/* 0x8a */
	RCKEY_DEF_VAL, 		/* 0x8b */
	RCKEY_DEF_VAL, 		/* 0x8c */
	RCKEY_DEF_VAL, 		/* 0x8d */
	RCKEY_DEF_VAL, 		/* 0x8e */
	RCKEY_DEF_VAL, 		/* 0x8f */
	RCKEY_DEF_VAL, 		/* 0x90 */
	RCKEY_DEF_VAL, 		/* 0x91 */
	RCKEY_DEF_VAL, 		/* 0x92 */
	RCKEY_DEF_VAL, 		/* 0x93 */
	RCKEY_DEF_VAL, 		/* 0x94 */
	RCKEY_DEF_VAL, 		/* 0x95 */
	RCKEY_DEF_VAL, 		/* 0x96 */
	RCKEY_DEF_VAL, 		/* 0x97 */
	RCKEY_DEF_VAL, 		/* 0x98 */
	RCKEY_DEF_VAL, 		/* 0x99 */
	RCKEY_DEF_VAL, 		/* 0x9a */
	RCKEY_DEF_VAL, 		/* 0x9b */
	RCKEY_DEF_VAL, 		/* 0x9c */
	RCKEY_DEF_VAL, 		/* 0x9d */
	RCKEY_DEF_VAL, 		/* 0x9e */
	RCKEY_DEF_VAL, 		/* 0x9f */
	RCKEY_DEF_VAL, 		/* 0xa0 */
	RCKEY_DEF_VAL, 		/* 0xa1 */
	RCKEY_DEF_VAL, 		/* 0xa2 */
	RCKEY_DEF_VAL, 		/* 0xa3 */
	RCKEY_DEF_VAL, 		/* 0xa4 */
	RCKEY_DEF_VAL, 		/* 0xa5 */
	RCKEY_DEF_VAL, 		/* 0xa6 */
	RCKEY_DEF_VAL, 		/* 0xa7 */
	RCKEY_DEF_VAL, 		/* 0xa8 */
	RCKEY_DEF_VAL, 		/* 0xa9 */
	RCKEY_DEF_VAL, 		/* 0xaa */
	RCKEY_DEF_VAL, 		/* 0xab */
	RCKEY_DEF_VAL, 		/* 0xac */
	RCKEY_DEF_VAL, 		/* 0xad */
	RCKEY_DEF_VAL, 		/* 0xae */
	RCKEY_DEF_VAL, 		/* 0xaf */
	RCKEY_DEF_VAL, 		/* 0xb0 */
	RCKEY_DEF_VAL, 		/* 0xb1 */
	RCKEY_DEF_VAL, 		/* 0xb2 */
	RCKEY_DEF_VAL, 		/* 0xb3 */
	RCKEY_DEF_VAL, 		/* 0xb4 */
	RCKEY_DEF_VAL, 		/* 0xb5 */
	RCKEY_DEF_VAL, 		/* 0xb6 */
	RCKEY_DEF_VAL, 		/* 0xb7 */
	RCKEY_DEF_VAL, 		/* 0xb8 */
	RCKEY_DEF_VAL, 		/* 0xb9 */
	RCKEY_DEF_VAL, 		/* 0xba */
	RCKEY_DEF_VAL, 		/* 0xbb */
	RCKEY_DEF_VAL, 		/* 0xbc */
	RCKEY_DEF_VAL, 		/* 0xbd */
	RCKEY_DEF_VAL, 		/* 0xbe */
	RCKEY_DEF_VAL, 		/* 0xbf */
	RCKEY_DEF_VAL, 		/* 0xc0 */
	RCKEY_DEF_VAL, 		/* 0xc1 */
	RCKEY_DEF_VAL, 		/* 0xc2 */
	RCKEY_DEF_VAL, 		/* 0xc3 */
	RCKEY_DEF_VAL, 		/* 0xc4 */
	RCKEY_DEF_VAL, 		/* 0xc5 */
	RCKEY_DEF_VAL, 		/* 0xc6 */
	RCKEY_DEF_VAL, 		/* 0xc7 */
	RCKEY_DEF_VAL, 		/* 0xc8 */
	RCKEY_DEF_VAL, 		/* 0xc9 */
	RCKEY_DEF_VAL, 		/* 0xca */
	RCKEY_DEF_VAL, 		/* 0xcb */
	RCKEY_DEF_VAL, 		/* 0xcc */
	RCKEY_DEF_VAL, 		/* 0xcd */
	RCKEY_DEF_VAL, 		/* 0xce */
	RCKEY_DEF_VAL, 		/* 0xcf */
	RCKEY_DEF_VAL, 		/* 0xd0 */
	RCKEY_DEF_VAL, 		/* 0xd1 */
	RCKEY_DEF_VAL, 		/* 0xd2 */
	RCKEY_DEF_VAL, 		/* 0xd3 */
	RCKEY_DEF_VAL, 		/* 0xd4 */
	RCKEY_DEF_VAL, 		/* 0xd5 */
	RCKEY_DEF_VAL, 		/* 0xd6 */
	RCKEY_DEF_VAL, 		/* 0xd7 */
	RCKEY_DEF_VAL, 		/* 0xd8 */
	RCKEY_DEF_VAL, 		/* 0xd9 */
	RCKEY_DEF_VAL, 		/* 0xda */
	RCKEY_DEF_VAL, 		/* 0xdb */
	RCKEY_DEF_VAL, 		/* 0xdc */
	RCKEY_DEF_VAL, 		/* 0xdd */
	RCKEY_DEF_VAL, 		/* 0xde */
	RCKEY_DEF_VAL, 		/* 0xdf */
	RCKEY_DEF_VAL, 		/* 0xe0 */
	RCKEY_DEF_VAL, 		/* 0xe1 */
	RCKEY_DEF_VAL, 		/* 0xe2 */
	RCKEY_DEF_VAL, 		/* 0xe3 */
	RCKEY_DEF_VAL, 		/* 0xe4 */
	RCKEY_DEF_VAL, 		/* 0xe5 */
	RCKEY_DEF_VAL, 		/* 0xe6 */
	RCKEY_DEF_VAL, 		/* 0xe7 */
	RCKEY_DEF_VAL, 		/* 0xe8 */
	RCKEY_DEF_VAL, 		/* 0xe9 */
	RCKEY_DEF_VAL, 		/* 0xea */
	RCKEY_DEF_VAL, 		/* 0xeb */
	RCKEY_DEF_VAL, 		/* 0xec */
	RCKEY_DEF_VAL, 		/* 0xed */
	RCKEY_DEF_VAL, 		/* 0xee */
	RCKEY_DEF_VAL, 		/* 0xef */
	RCKEY_DEF_VAL, 		/* 0xf0 */
	RCKEY_DEF_VAL, 		/* 0xf1 */
	RCKEY_DEF_VAL, 		/* 0xf2 */
	RCKEY_DEF_VAL, 		/* 0xf3 */
	RCKEY_DEF_VAL, 		/* 0xf4 */
	RCKEY_DEF_VAL, 		/* 0xf5 */
	RCKEY_DEF_VAL, 		/* 0xf6 */
	RCKEY_DEF_VAL, 		/* 0xf7 */
	RCKEY_DEF_VAL, 		/* 0xf8 */
	RCKEY_DEF_VAL, 		/* 0xf9 */
	RCKEY_DEF_VAL, 		/* 0xfa */
	RCKEY_DEF_VAL, 		/* 0xfb */
	RCKEY_DEF_VAL, 		/* 0xfc */
	RCKEY_DEF_VAL, 		/* 0xfd */
 	RCKEY_DEF_VAL, 		/* 0xfe */ 
  	RCKEY_DEF_VAL, 		/* 0xff */ 
  	RCKEY_DEF_VAL, 		/* 0x100 */ 
  	RCKEY_DEF_VAL, 		/* 0x101 */ 
  	RCKEY_DEF_VAL, 		/* 0x102 */ 
  	RCKEY_DEF_VAL, 		/* 0x103 */ 
  	RCKEY_DEF_VAL, 		/* 0x104 */ 
  	RCKEY_DEF_VAL, 		/* 0x105 */ 
  	RCKEY_DEF_VAL, 		/* 0x106 */ 
  	RCKEY_DEF_VAL, 		/* 0x107 */ 
  	RCKEY_DEF_VAL, 		/* 0x108 */ 
  	RCKEY_DEF_VAL, 		/* 0x109 */ 
  	RCKEY_DEF_VAL, 		/* 0x10a */ 
  	RCKEY_DEF_VAL, 		/* 0x10b */ 
  	RCKEY_DEF_VAL, 		/* 0x10c */ 
  	RCKEY_DEF_VAL, 		/* 0x10d */ 
  	RCKEY_DEF_VAL, 		/* 0x10e */ 
  	RCKEY_DEF_VAL, 		/* 0x10f */ 
  	RCKEY_DEF_VAL, 		/* 0x110 */ 
  	RCKEY_DEF_VAL, 		/* 0x111 */ 
  	RCKEY_DEF_VAL, 		/* 0x112 */ 
  	RCKEY_DEF_VAL, 		/* 0x113 */ 
  	RCKEY_DEF_VAL, 		/* 0x114 */ 
  	RCKEY_DEF_VAL, 		/* 0x115 */ 
  	RCKEY_DEF_VAL, 		/* 0x116 */ 
  	RCKEY_DEF_VAL, 		/* 0x117 */ 
  	RCKEY_DEF_VAL, 		/* 0x118 */ 
  	RCKEY_DEF_VAL, 		/* 0x119 */ 
  	RCKEY_DEF_VAL, 		/* 0x11a */ 
  	RCKEY_DEF_VAL, 		/* 0x11b */ 
  	RCKEY_DEF_VAL, 		/* 0x11c */ 
  	RCKEY_DEF_VAL, 		/* 0x11d */ 
  	RCKEY_DEF_VAL, 		/* 0x11e */ 
  	SCANCODE_CURSORDOWN, 		/* 0x11f : Front Down */ 
  	RCKEY_DEF_VAL, 		/* 0x120 */ 
  	RCKEY_DEF_VAL, 		/* 0x121 */ 
  	RCKEY_DEF_VAL, 		/* 0x122 */ 
  	RCKEY_DEF_VAL, 		/* 0x123 */ 
  	RCKEY_DEF_VAL, 		/* 0x124 */ 
  	RCKEY_DEF_VAL, 		/* 0x125 */ 
  	RCKEY_DEF_VAL, 		/* 0x126 */ 
  	RCKEY_DEF_VAL, 		/* 0x127 */ 
  	RCKEY_DEF_VAL, 		/* 0x128 */ 
  	RCKEY_DEF_VAL, 		/* 0x129 */ 
  	RCKEY_DEF_VAL, 		/* 0x12a */ 
  	RCKEY_DEF_VAL, 		/* 0x12b */ 
  	RCKEY_DEF_VAL, 		/* 0x12c */ 
  	RCKEY_DEF_VAL, 		/* 0x12d */ 
  	RCKEY_DEF_VAL, 		/* 0x12e */ 
  	SCANCODE_CURSORUP, 		/* 0x12f : Front Up */ 
  	RCKEY_DEF_VAL, 		/* 0x130 */ 
  	RCKEY_DEF_VAL, 		/* 0x131 */ 
  	RCKEY_DEF_VAL, 		/* 0x132 */ 
  	RCKEY_DEF_VAL, 		/* 0x133 */ 
  	RCKEY_DEF_VAL, 		/* 0x134 */ 
  	RCKEY_DEF_VAL, 		/* 0x135 */ 
  	RCKEY_DEF_VAL, 		/* 0x136 */ 
  	SCANCODE_CURSORRIGHT, 		/* 0x137 : Front Right */ 
  	RCKEY_DEF_VAL, 		/* 0x138 */ 
  	RCKEY_DEF_VAL, 		/* 0x139 */ 
  	RCKEY_DEF_VAL, 		/* 0x13a */ 
  	SCANCODE_CURSORLEFT, 		/* 0x13b : Front Left */ 
  	RCKEY_DEF_VAL, 		/* 0x13c */ 
  	SCANCODE_ENTER, 		/* 0x13d  : Front OK */ 
  	SCANCODE_F1, 		/* 0x13e  : Front Menu */ 
  	RCKEY_DEF_VAL, 		/* 0x13f */ 
  	RCKEY_DEF_VAL, 		/* 0x140 */ 
  	RCKEY_DEF_VAL, 		/* 0x141 */ 
  	RCKEY_DEF_VAL, 		/* 0x142 */ 
  	RCKEY_DEF_VAL, 		/* 0x143 */ 
  	RCKEY_DEF_VAL, 		/* 0x144 */ 
  	RCKEY_DEF_VAL, 		/* 0x145 */ 
  	RCKEY_DEF_VAL, 		/* 0x146 */ 
  	RCKEY_DEF_VAL, 		/* 0x147 */ 
  	RCKEY_DEF_VAL, 		/* 0x148 */ 
  	RCKEY_DEF_VAL, 		/* 0x149 */ 
  	RCKEY_DEF_VAL, 		/* 0x14a */ 
  	RCKEY_DEF_VAL, 		/* 0x14b */ 
  	RCKEY_DEF_VAL, 		/* 0x14c */ 
  	RCKEY_DEF_VAL, 		/* 0x14d */ 
  	RCKEY_DEF_VAL, 		/* 0x14e */ 
  	RCKEY_DEF_VAL, 		/* 0x14f */ 
  	RCKEY_DEF_VAL, 		/* 0x150 */ 
  	RCKEY_DEF_VAL, 		/* 0x151 */ 
  	RCKEY_DEF_VAL, 		/* 0x152 */ 
  	RCKEY_DEF_VAL, 		/* 0x153 */ 
  	RCKEY_DEF_VAL, 		/* 0x154 */ 
  	RCKEY_DEF_VAL, 		/* 0x155 */ 
  	RCKEY_DEF_VAL, 		/* 0x156 */ 
  	RCKEY_DEF_VAL, 		/* 0x157 */ 
  	RCKEY_DEF_VAL, 		/* 0x158 */ 
  	RCKEY_DEF_VAL, 		/* 0x159 */ 
  	RCKEY_DEF_VAL, 		/* 0x15a */ 
  	RCKEY_DEF_VAL, 		/* 0x15b */ 
  	RCKEY_DEF_VAL, 		/* 0x15c */ 
  	RCKEY_DEF_VAL, 		/* 0x15d */ 
  	RCKEY_DEF_VAL, 		/* 0x15e */ 
  	RCKEY_DEF_VAL, 		/* 0x15f */ 
  	RCKEY_DEF_VAL, 		/* 0x160 */ 
  	RCKEY_DEF_VAL, 		/* 0x161 */ 
  	RCKEY_DEF_VAL, 		/* 0x162 */ 
  	RCKEY_DEF_VAL, 		/* 0x163 */ 
  	RCKEY_DEF_VAL, 		/* 0x164 */ 
  	RCKEY_DEF_VAL, 		/* 0x165 */ 
  	RCKEY_DEF_VAL, 		/* 0x166 */ 
  	RCKEY_DEF_VAL, 		/* 0x167 */ 
  	RCKEY_DEF_VAL, 		/* 0x168 */ 
  	RCKEY_DEF_VAL, 		/* 0x169 */ 
  	RCKEY_DEF_VAL, 		/* 0x16a */ 
  	RCKEY_DEF_VAL, 		/* 0x16b */ 
  	RCKEY_DEF_VAL, 		/* 0x16c */ 
  	RCKEY_DEF_VAL, 		/* 0x16d */ 
  	RCKEY_DEF_VAL, 		/* 0x16e */ 
  	RCKEY_DEF_VAL, 		/* 0x16f */ 
  	RCKEY_DEF_VAL, 		/* 0x170 */ 
  	RCKEY_DEF_VAL, 		/* 0x171 */ 
  	RCKEY_DEF_VAL, 		/* 0x172 */ 
  	RCKEY_DEF_VAL, 		/* 0x173 */ 
  	RCKEY_DEF_VAL, 		/* 0x174 */ 
  	RCKEY_DEF_VAL, 		/* 0x175 */ 
  	RCKEY_DEF_VAL, 		/* 0x176 */ 
  	RCKEY_DEF_VAL, 		/* 0x177 */ 
  	RCKEY_DEF_VAL, 		/* 0x178 */ 
  	RCKEY_DEF_VAL, 		/* 0x179 */ 
  	RCKEY_DEF_VAL, 		/* 0x17a */ 
  	RCKEY_DEF_VAL, 		/* 0x17b */ 
  	RCKEY_DEF_VAL, 		/* 0x17c */ 
  	RCKEY_DEF_VAL, 		/* 0x17d */ 
  	RCKEY_DEF_VAL, 		/* 0x17e */ 
  	RCKEY_DEF_VAL, 		/* 0x17f */ 
  	RCKEY_DEF_VAL, 		/* 0x180 */ 
  	RCKEY_DEF_VAL, 		/* 0x181 */ 
  	RCKEY_DEF_VAL, 		/* 0x182 */ 
  	RCKEY_DEF_VAL, 		/* 0x183 */ 
  	RCKEY_DEF_VAL, 		/* 0x184 */ 
  	RCKEY_DEF_VAL, 		/* 0x185 */ 
  	RCKEY_DEF_VAL, 		/* 0x186 */ 
  	RCKEY_DEF_VAL, 		/* 0x187 */ 
  	RCKEY_DEF_VAL, 		/* 0x188 */ 
  	RCKEY_DEF_VAL, 		/* 0x189 */ 
  	RCKEY_DEF_VAL, 		/* 0x18a */ 
  	RCKEY_DEF_VAL, 		/* 0x18b */ 
  	RCKEY_DEF_VAL, 		/* 0x18c */ 
  	RCKEY_DEF_VAL, 		/* 0x18d */ 
  	RCKEY_DEF_VAL, 		/* 0x18e */ 
  	RCKEY_DEF_VAL, 		/* 0x18f */ 
  	RCKEY_DEF_VAL, 		/* 0x190 */ 
  	RCKEY_DEF_VAL, 		/* 0x191 */ 
  	RCKEY_DEF_VAL, 		/* 0x192 */ 
  	RCKEY_DEF_VAL, 		/* 0x193 */ 
  	RCKEY_DEF_VAL, 		/* 0x194 */ 
  	RCKEY_DEF_VAL, 		/* 0x195 */ 
  	RCKEY_DEF_VAL, 		/* 0x196 */ 
  	RCKEY_DEF_VAL, 		/* 0x197 */ 
  	RCKEY_DEF_VAL, 		/* 0x198 */ 
  	RCKEY_DEF_VAL, 		/* 0x199 */ 
  	RCKEY_DEF_VAL, 		/* 0x19a */ 
  	RCKEY_DEF_VAL, 		/* 0x19b */ 
  	RCKEY_DEF_VAL, 		/* 0x19c */ 
  	RCKEY_DEF_VAL, 		/* 0x19d */ 
  	RCKEY_DEF_VAL, 		/* 0x19e */ 
  	RCKEY_DEF_VAL, 		/* 0x19f */ 
  	RCKEY_DEF_VAL, 		/* 0x1a0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1aa */ 
  	RCKEY_DEF_VAL, 		/* 0x1ab */ 
  	RCKEY_DEF_VAL, 		/* 0x1ac */ 
  	RCKEY_DEF_VAL, 		/* 0x1ad */ 
  	RCKEY_DEF_VAL, 		/* 0x1ae */ 
  	RCKEY_DEF_VAL, 		/* 0x1af */ 
  	RCKEY_DEF_VAL, 		/* 0x1b0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ba */ 
  	RCKEY_DEF_VAL, 		/* 0x1bb */ 
  	RCKEY_DEF_VAL, 		/* 0x1bc */ 
  	RCKEY_DEF_VAL, 		/* 0x1bd */ 
  	RCKEY_DEF_VAL, 		/* 0x1be */ 
  	RCKEY_DEF_VAL, 		/* 0x1bf */ 
  	RCKEY_DEF_VAL, 		/* 0x1c0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ca */ 
  	RCKEY_DEF_VAL, 		/* 0x1cb */ 
  	RCKEY_DEF_VAL, 		/* 0x1cc */ 
  	RCKEY_DEF_VAL, 		/* 0x1cd */ 
  	RCKEY_DEF_VAL, 		/* 0x1ce */ 
  	RCKEY_DEF_VAL, 		/* 0x1cf */ 
  	RCKEY_DEF_VAL, 		/* 0x1d0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1da */ 
  	RCKEY_DEF_VAL, 		/* 0x1db */ 
  	RCKEY_DEF_VAL, 		/* 0x1dc */ 
  	RCKEY_DEF_VAL, 		/* 0x1dd */ 
  	RCKEY_DEF_VAL, 		/* 0x1de */ 
  	RCKEY_DEF_VAL, 		/* 0x1df */ 
  	RCKEY_DEF_VAL, 		/* 0x1e0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ea */ 
  	RCKEY_DEF_VAL, 		/* 0x1eb */ 
  	RCKEY_DEF_VAL, 		/* 0x1ec */ 
  	RCKEY_DEF_VAL, 		/* 0x1ed */ 
  	RCKEY_DEF_VAL, 		/* 0x1ee */ 
  	RCKEY_DEF_VAL, 		/* 0x1ef */ 
  	RCKEY_DEF_VAL, 		/* 0x1f0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1fa */ 
  	RCKEY_DEF_VAL, 		/* 0x1fb */ 
  	RCKEY_DEF_VAL, 		/* 0x1fc */ 
  	RCKEY_DEF_VAL, 		/* 0x1fd */ 
  	CSAPI_USB_CONNECTION, 	/* 0x1fe */ 
};
#else
int basic_keycodes[] = {
	RCKEY_DEF_VAL, 		/* 0x00 */
	RCKEY_DEF_VAL, 		/* 0x01 */
	RCKEY_DEF_VAL, 		/* 0x02 */
	RCKEY_DEF_VAL, 		/* 0x03 */
	RCKEY_DEF_VAL, 		/* 0x04 */
	RCKEY_DEF_VAL, 		/* 0x05 */
	RCKEY_DEF_VAL,  	/* 0x06 */
	RCKEY_DEF_VAL, 		/* 0x07 */
	SCANCODE_3, 		/* 0x08 */
	RCKEY_DEF_VAL, 		/* 0x09 */
	SCANCODE_2, 		/* 0x0a */
	RCKEY_DEF_VAL, 		/* 0x0b */
	RCKEY_DEF_VAL, 		/* 0x0c */
	RCKEY_DEF_VAL, 	/* 0x0d */
	RCKEY_DEF_VAL, 		/* 0x0e */
	RCKEY_DEF_VAL, 		/* 0x0f */
	SCANCODE_O, 		/* 0x10 */
	RCKEY_DEF_VAL, 		/* 0x11 */
	SCANCODE_N, 		/* 0x12 */
	RCKEY_DEF_VAL, 		/* 0x13 */
	RCKEY_DEF_VAL, 		/* 0x14 */
	RCKEY_DEF_VAL, 		/* 0x15 */
	RCKEY_DEF_VAL, 	/* 0x16 */
	RCKEY_DEF_VAL, 		/* 0x17 */
	RCKEY_DEF_VAL, 		/* 0x18 */
	RCKEY_DEF_VAL, 		/* 0x19 */
	RCKEY_DEF_VAL, 	/* 0x1a */
	RCKEY_DEF_VAL, 	/* 0x1b */
	RCKEY_DEF_VAL, 		/* 0x1c */
	RCKEY_DEF_VAL, 		/* 0x1d */
	RCKEY_DEF_VAL, 		/* 0x1e */
	RCKEY_DEF_VAL, 		/* 0x1f */
	RCKEY_DEF_VAL, 		/* 0x20 */
	RCKEY_DEF_VAL, 		/* 0x21 */
	RCKEY_DEF_VAL, 		/* 0x22 */
	RCKEY_DEF_VAL, 		/* 0x23 */
	RCKEY_DEF_VAL, 		/* 0x24 */
	RCKEY_DEF_VAL, 		/* 0x25 */
	RCKEY_DEF_VAL, 		/* 0x26 */
	RCKEY_DEF_VAL, 		/* 0x27 */
	SCANCODE_7, 		/* 0x28 */
	RCKEY_DEF_VAL, 		/* 0x29 */
	SCANCODE_6, 		/* 0x2a */
	RCKEY_DEF_VAL, 		/* 0x2b */
	RCKEY_DEF_VAL, 		/* 0x2c */
	RCKEY_DEF_VAL, 		/* 0x2d */
	RCKEY_DEF_VAL, 		/* 0x2e */
	RCKEY_DEF_VAL, 		/* 0x2f */
	SCANCODE_K, 		/* 0x30 */
	RCKEY_DEF_VAL, 		/* 0x31 */
	SCANCODE_0, 		/* 0x32 */
	RCKEY_DEF_VAL, 		/* 0x33 */
	RCKEY_DEF_VAL, 		/* 0x34 */
	RCKEY_DEF_VAL, 		/* 0x35 */
	RCKEY_DEF_VAL, 		/* 0x36 */
	RCKEY_DEF_VAL, 		/* 0x37 */
	RCKEY_DEF_VAL, 		/* 0x38 */
	RCKEY_DEF_VAL, 		/* 0x39 */
	RCKEY_DEF_VAL, 		/* 0x3a */
	RCKEY_DEF_VAL, 		/* 0x3b */
	RCKEY_DEF_VAL, 		/* 0x3c */
	RCKEY_DEF_VAL, 		/* 0x3d */
	RCKEY_DEF_VAL, 		/* 0x3e */
	RCKEY_DEF_VAL, 		/* 0x3f */
	RCKEY_DEF_VAL, 		/* 0x40 */
	RCKEY_DEF_VAL, 		/* 0x41 */
	RCKEY_DEF_VAL, 		/* 0x42 */
	RCKEY_DEF_VAL, 		/* 0x43 */
	RCKEY_DEF_VAL, 		/* 0x44 */
	RCKEY_DEF_VAL, 		/* 0x45 */
	RCKEY_DEF_VAL, 		/* 0x46 */
	RCKEY_DEF_VAL, 		/* 0x47 */
	SCANCODE_E, 		/* 0x48 */
	RCKEY_DEF_VAL, 		/* 0x49 */
	SCANCODE_1, 		/* 0x4a */
	RCKEY_DEF_VAL, 		/* 0x4b */
	RCKEY_DEF_VAL, 		/* 0x4c */
	RCKEY_DEF_VAL, 		/* 0x4d */
	RCKEY_DEF_VAL, 		/* 0x4e */
	RCKEY_DEF_VAL, 		/* 0x4f */
	RCKEY_DEF_VAL, 		/* 0x50 */
	RCKEY_DEF_VAL, 		/* 0x51 */
	SCANCODE_M, 		/* 0x52 */
	RCKEY_DEF_VAL, 		/* 0x53 */
	RCKEY_DEF_VAL, 		/* 0x54 */
	RCKEY_DEF_VAL, 		/* 0x55 */
	RCKEY_DEF_VAL, 		/* 0x56 */
	RCKEY_DEF_VAL, 		/* 0x57 */
	SCANCODE_ENTER, 		/* 0x58 */
	RCKEY_DEF_VAL, 		/* 0x59 */
	SCANCODE_CURSORLEFT, 	/* 0x5a */
	RCKEY_DEF_VAL, 		/* 0x5b */
	RCKEY_DEF_VAL, 		/* 0x5c */
	RCKEY_DEF_VAL, 		/* 0x5d */
	RCKEY_DEF_VAL, 		/* 0x5e */
	RCKEY_DEF_VAL, 		/* 0x5f */
	SCANCODE_CURSORUP, 		/* 0x60 */
	RCKEY_DEF_VAL, 		/* 0x61 */
	RCKEY_DEF_VAL, 		/* 0x62 */
	RCKEY_DEF_VAL, 		/* 0x63 */
	RCKEY_DEF_VAL, 		/* 0x64 */
	RCKEY_DEF_VAL, 		/* 0x65 */
	RCKEY_DEF_VAL, 		/* 0x66 */
	RCKEY_DEF_VAL, 		/* 0x67 */
	SCANCODE_CURSORDOWN, 		/* 0x68 */
	RCKEY_DEF_VAL, 		/* 0x69 */
	SCANCODE_5, 		/* 0x6a */
	RCKEY_DEF_VAL, 		/* 0x6b */
	RCKEY_DEF_VAL, 		/* 0x6c */
	RCKEY_DEF_VAL, 		/* 0x6d */
	RCKEY_DEF_VAL, 		/* 0x6e */
	RCKEY_DEF_VAL, 		/* 0x6f */
	SCANCODE_C, 		/* 0x70 */
	RCKEY_DEF_VAL, 		/* 0x71 */
	SCANCODE_9, 		/* 0x72 */
	RCKEY_DEF_VAL, 		/* 0x73 */
	RCKEY_DEF_VAL, 		/* 0x74 */
	RCKEY_DEF_VAL, 		/* 0x75 */
	RCKEY_DEF_VAL, 		/* 0x76 */
	RCKEY_DEF_VAL, 		/* 0x77 */
	RCKEY_DEF_VAL, 		/* 0x78 */
	RCKEY_DEF_VAL, 		/* 0x79 */
	RCKEY_DEF_VAL, 		/* 0x7a */
	RCKEY_DEF_VAL, 		/* 0x7b */
	RCKEY_DEF_VAL, 		/* 0x7c */
	RCKEY_DEF_VAL, 		/* 0x7d */
	RCKEY_DEF_VAL, 		/* 0x7e */
	RCKEY_DEF_VAL, 		/* 0x7f */
	RCKEY_DEF_VAL, 		/* 0x80 */
	RCKEY_DEF_VAL, 		/* 0x81 */
	RCKEY_DEF_VAL, 		/* 0x82 */
	RCKEY_DEF_VAL, 		/* 0x83 */
	RCKEY_DEF_VAL, 		/* 0x84 */
	RCKEY_DEF_VAL, 		/* 0x85 */
	RCKEY_DEF_VAL, 		/* 0x86 */
	RCKEY_DEF_VAL, 		/* 0x87 */
	SCANCODE_F, 		/* 0x88 */
	RCKEY_DEF_VAL, 		/* 0x89 */
	SCANCODE_D, 		/* 0x8a */
	RCKEY_DEF_VAL, 		/* 0x8b */
	RCKEY_DEF_VAL, 		/* 0x8c */
	RCKEY_DEF_VAL, 		/* 0x8d */
	RCKEY_DEF_VAL, 		/* 0x8e */
	RCKEY_DEF_VAL, 		/* 0x8f */
	RCKEY_DEF_VAL, 		/* 0x90 */
	RCKEY_DEF_VAL, 		/* 0x91 */
	RCKEY_DEF_VAL, 		/* 0x92 */
	RCKEY_DEF_VAL, 		/* 0x93 */
	RCKEY_DEF_VAL, 		/* 0x94 */
	RCKEY_DEF_VAL, 		/* 0x95 */
	RCKEY_DEF_VAL, 		/* 0x96 */
	RCKEY_DEF_VAL, 		/* 0x97 */
	SCANCODE_B, 		/* 0x98 */
	RCKEY_DEF_VAL, 		/* 0x99 */
	SCANCODE_A, 		/* 0x9a */
	RCKEY_DEF_VAL, 		/* 0x9b */
	RCKEY_DEF_VAL, 		/* 0x9c */
	RCKEY_DEF_VAL, 		/* 0x9d */
	RCKEY_DEF_VAL, 		/* 0x9e */
	RCKEY_DEF_VAL, 		/* 0x9f */
	SCANCODE_H, 		/* 0xa0 */
	RCKEY_DEF_VAL, 		/* 0xa1 */
	SCANCODE_G, 		/* 0xa2 */
	RCKEY_DEF_VAL, 		/* 0xa3 */
	RCKEY_DEF_VAL, 		/* 0xa4 */
	RCKEY_DEF_VAL, 		/* 0xa5 */
	RCKEY_DEF_VAL, 		/* 0xa6 */
	RCKEY_DEF_VAL, 		/* 0xa7 */
	SCANCODE_J, 		/* 0xa8 */
	RCKEY_DEF_VAL, 		/* 0xa9 */
	SCANCODE_I, 		/* 0xaa */
	RCKEY_DEF_VAL, 		/* 0xab */
	RCKEY_DEF_VAL, 		/* 0xac */
	RCKEY_DEF_VAL, 		/* 0xad */
	RCKEY_DEF_VAL, 		/* 0xae */
	RCKEY_DEF_VAL, 		/* 0xaf */
	SCANCODE_ESCAPE, 		/* 0xb0 */
	RCKEY_DEF_VAL, 		/* 0xb1 */
	SCANCODE_F1, 		/* 0xb2 */
	RCKEY_DEF_VAL, 		/* 0xb3 */
	RCKEY_DEF_VAL, 		/* 0xb4 */
	RCKEY_DEF_VAL, 		/* 0xb5 */
	RCKEY_DEF_VAL, 		/* 0xb6 */
	RCKEY_DEF_VAL, 		/* 0xb7 */
	RCKEY_DEF_VAL, 		/* 0xb8 */
	RCKEY_DEF_VAL, 		/* 0xb9 */
	RCKEY_DEF_VAL, 		/* 0xba */
	RCKEY_DEF_VAL, 		/* 0xbb */
	RCKEY_DEF_VAL, 		/* 0xbc */
	RCKEY_DEF_VAL, 		/* 0xbd */
	RCKEY_DEF_VAL, 		/* 0xbe */
	RCKEY_DEF_VAL, 		/* 0xbf */
	RCKEY_DEF_VAL, 		/* 0xc0 */
	RCKEY_DEF_VAL, 		/* 0xc1 */
	RCKEY_DEF_VAL, 		/* 0xc2 */
	RCKEY_DEF_VAL, 		/* 0xc3 */
	RCKEY_DEF_VAL, 		/* 0xc4 */
	RCKEY_DEF_VAL, 		/* 0xc5 */
	RCKEY_DEF_VAL, 		/* 0xc6 */
	RCKEY_DEF_VAL, 		/* 0xc7 */
	SCANCODE_4, 		/* 0xc8 */
	RCKEY_DEF_VAL, 		/* 0xc9 */
	RCKEY_DEF_VAL, 		/* 0xca */
	RCKEY_DEF_VAL, 		/* 0xcb */
	RCKEY_DEF_VAL, 		/* 0xcc */
	RCKEY_DEF_VAL, 		/* 0xcd */
	RCKEY_DEF_VAL, 		/* 0xce */
	RCKEY_DEF_VAL, 		/* 0xcf */
	SCANCODE_P, 		/* 0xd0 */
	RCKEY_DEF_VAL, 		/* 0xd1 */
	RCKEY_DEF_VAL, 		/* 0xd2 */
	RCKEY_DEF_VAL, 		/* 0xd3 */
	RCKEY_DEF_VAL, 		/* 0xd4 */
	RCKEY_DEF_VAL, 		/* 0xd5 */
	RCKEY_DEF_VAL, 		/* 0xd6 */
	RCKEY_DEF_VAL, 		/* 0xd7 */
	SCANCODE_CURSORRIGHT, 		/* 0xd8 */
	RCKEY_DEF_VAL, 		/* 0xd9 */
	RCKEY_DEF_VAL, 		/* 0xda */
	RCKEY_DEF_VAL, 		/* 0xdb */
	RCKEY_DEF_VAL, 		/* 0xdc */
	RCKEY_DEF_VAL, 		/* 0xdd */
	RCKEY_DEF_VAL, 		/* 0xde */
	RCKEY_DEF_VAL, 		/* 0xdf */
	RCKEY_DEF_VAL, 		/* 0xe0 */
	RCKEY_DEF_VAL, 		/* 0xe1 */
	RCKEY_DEF_VAL, 		/* 0xe2 */
	RCKEY_DEF_VAL, 		/* 0xe3 */
	RCKEY_DEF_VAL, 		/* 0xe4 */
	RCKEY_DEF_VAL, 		/* 0xe5 */
	RCKEY_DEF_VAL, 		/* 0xe6 */
	RCKEY_DEF_VAL, 		/* 0xe7 */
	SCANCODE_8, 		/* 0xe8 */
	RCKEY_DEF_VAL, 		/* 0xe9 */
	RCKEY_DEF_VAL, 		/* 0xea */
	RCKEY_DEF_VAL, 		/* 0xeb */
	RCKEY_DEF_VAL, 		/* 0xec */
	RCKEY_DEF_VAL, 		/* 0xed */
	RCKEY_DEF_VAL, 		/* 0xee */
	RCKEY_DEF_VAL, 		/* 0xef */
	SCANCODE_L, 		/* 0xf0 */
	RCKEY_DEF_VAL, 		/* 0xf1 */
	RCKEY_DEF_VAL, 		/* 0xf2 */
	RCKEY_DEF_VAL, 		/* 0xf3 */
	RCKEY_DEF_VAL, 		/* 0xf4 */
	RCKEY_DEF_VAL, 		/* 0xf5 */
	RCKEY_DEF_VAL, 		/* 0xf6 */
	RCKEY_DEF_VAL, 		/* 0xf7 */
	RCKEY_DEF_VAL, 		/* 0xf8 */
	RCKEY_DEF_VAL, 		/* 0xf9 */
	RCKEY_DEF_VAL, 		/* 0xfa */
	RCKEY_DEF_VAL, 		/* 0xfb */
	RCKEY_DEF_VAL, 		/* 0xfc */
	RCKEY_DEF_VAL, 		/* 0xfd */
 	RCKEY_DEF_VAL, 		/* 0xfe */ 
  	RCKEY_DEF_VAL, 		/* 0xff */ 
  	RCKEY_DEF_VAL, 		/* 0x100 */ 
  	RCKEY_DEF_VAL, 		/* 0x101 */ 
  	RCKEY_DEF_VAL, 		/* 0x102 */ 
  	RCKEY_DEF_VAL, 		/* 0x103 */ 
  	RCKEY_DEF_VAL, 		/* 0x104 */ 
  	RCKEY_DEF_VAL, 		/* 0x105 */ 
  	RCKEY_DEF_VAL, 		/* 0x106 */ 
  	RCKEY_DEF_VAL, 		/* 0x107 */ 
  	RCKEY_DEF_VAL, 		/* 0x108 */ 
  	RCKEY_DEF_VAL, 		/* 0x109 */ 
  	RCKEY_DEF_VAL, 		/* 0x10a */ 
  	RCKEY_DEF_VAL, 		/* 0x10b */ 
  	RCKEY_DEF_VAL, 		/* 0x10c */ 
  	RCKEY_DEF_VAL, 		/* 0x10d */ 
  	RCKEY_DEF_VAL, 		/* 0x10e */ 
  	RCKEY_DEF_VAL, 		/* 0x10f */ 
  	RCKEY_DEF_VAL, 		/* 0x110 */ 
  	RCKEY_DEF_VAL, 		/* 0x111 */ 
  	RCKEY_DEF_VAL, 		/* 0x112 */ 
  	RCKEY_DEF_VAL, 		/* 0x113 */ 
  	RCKEY_DEF_VAL, 		/* 0x114 */ 
  	RCKEY_DEF_VAL, 		/* 0x115 */ 
  	RCKEY_DEF_VAL, 		/* 0x116 */ 
  	RCKEY_DEF_VAL, 		/* 0x117 */ 
  	RCKEY_DEF_VAL, 		/* 0x118 */ 
  	RCKEY_DEF_VAL, 		/* 0x119 */ 
  	RCKEY_DEF_VAL, 		/* 0x11a */ 
  	RCKEY_DEF_VAL, 		/* 0x11b */ 
  	RCKEY_DEF_VAL, 		/* 0x11c */ 
  	RCKEY_DEF_VAL, 		/* 0x11d */ 
  	RCKEY_DEF_VAL, 		/* 0x11e */ 
  	SCANCODE_CURSORDOWN, 		/* 0x11f : Front Down */ 
  	RCKEY_DEF_VAL, 		/* 0x120 */ 
  	RCKEY_DEF_VAL, 		/* 0x121 */ 
  	RCKEY_DEF_VAL, 		/* 0x122 */ 
  	RCKEY_DEF_VAL, 		/* 0x123 */ 
  	RCKEY_DEF_VAL, 		/* 0x124 */ 
  	RCKEY_DEF_VAL, 		/* 0x125 */ 
  	RCKEY_DEF_VAL, 		/* 0x126 */ 
  	RCKEY_DEF_VAL, 		/* 0x127 */ 
  	RCKEY_DEF_VAL, 		/* 0x128 */ 
  	RCKEY_DEF_VAL, 		/* 0x129 */ 
  	RCKEY_DEF_VAL, 		/* 0x12a */ 
  	RCKEY_DEF_VAL, 		/* 0x12b */ 
  	RCKEY_DEF_VAL, 		/* 0x12c */ 
  	RCKEY_DEF_VAL, 		/* 0x12d */ 
  	RCKEY_DEF_VAL, 		/* 0x12e */ 
  	SCANCODE_CURSORUP, 		/* 0x12f : Front Up */ 
  	RCKEY_DEF_VAL, 		/* 0x130 */ 
  	RCKEY_DEF_VAL, 		/* 0x131 */ 
  	RCKEY_DEF_VAL, 		/* 0x132 */ 
  	RCKEY_DEF_VAL, 		/* 0x133 */ 
  	RCKEY_DEF_VAL, 		/* 0x134 */ 
  	RCKEY_DEF_VAL, 		/* 0x135 */ 
  	RCKEY_DEF_VAL, 		/* 0x136 */ 
  	SCANCODE_CURSORRIGHT, 		/* 0x137 : Front Right */ 
  	RCKEY_DEF_VAL, 		/* 0x138 */ 
  	RCKEY_DEF_VAL, 		/* 0x139 */ 
  	RCKEY_DEF_VAL, 		/* 0x13a */ 
  	SCANCODE_CURSORLEFT, 		/* 0x13b : Front Left */ 
  	RCKEY_DEF_VAL, 		/* 0x13c */ 
  	SCANCODE_ENTER, 		/* 0x13d  : Front OK */ 
  	SCANCODE_F1, 		/* 0x13e  : Front Menu */ 
  	RCKEY_DEF_VAL, 		/* 0x13f */ 
  	RCKEY_DEF_VAL, 		/* 0x140 */ 
  	RCKEY_DEF_VAL, 		/* 0x141 */ 
  	RCKEY_DEF_VAL, 		/* 0x142 */ 
  	RCKEY_DEF_VAL, 		/* 0x143 */ 
  	RCKEY_DEF_VAL, 		/* 0x144 */ 
  	RCKEY_DEF_VAL, 		/* 0x145 */ 
  	RCKEY_DEF_VAL, 		/* 0x146 */ 
  	RCKEY_DEF_VAL, 		/* 0x147 */ 
  	RCKEY_DEF_VAL, 		/* 0x148 */ 
  	RCKEY_DEF_VAL, 		/* 0x149 */ 
  	RCKEY_DEF_VAL, 		/* 0x14a */ 
  	RCKEY_DEF_VAL, 		/* 0x14b */ 
  	RCKEY_DEF_VAL, 		/* 0x14c */ 
  	RCKEY_DEF_VAL, 		/* 0x14d */ 
  	RCKEY_DEF_VAL, 		/* 0x14e */ 
  	RCKEY_DEF_VAL, 		/* 0x14f */ 
  	RCKEY_DEF_VAL, 		/* 0x150 */ 
  	RCKEY_DEF_VAL, 		/* 0x151 */ 
  	RCKEY_DEF_VAL, 		/* 0x152 */ 
  	RCKEY_DEF_VAL, 		/* 0x153 */ 
  	RCKEY_DEF_VAL, 		/* 0x154 */ 
  	RCKEY_DEF_VAL, 		/* 0x155 */ 
  	RCKEY_DEF_VAL, 		/* 0x156 */ 
  	RCKEY_DEF_VAL, 		/* 0x157 */ 
  	RCKEY_DEF_VAL, 		/* 0x158 */ 
  	RCKEY_DEF_VAL, 		/* 0x159 */ 
  	RCKEY_DEF_VAL, 		/* 0x15a */ 
  	RCKEY_DEF_VAL, 		/* 0x15b */ 
  	RCKEY_DEF_VAL, 		/* 0x15c */ 
  	RCKEY_DEF_VAL, 		/* 0x15d */ 
  	RCKEY_DEF_VAL, 		/* 0x15e */ 
  	RCKEY_DEF_VAL, 		/* 0x15f */ 
  	RCKEY_DEF_VAL, 		/* 0x160 */ 
  	RCKEY_DEF_VAL, 		/* 0x161 */ 
  	RCKEY_DEF_VAL, 		/* 0x162 */ 
  	RCKEY_DEF_VAL, 		/* 0x163 */ 
  	RCKEY_DEF_VAL, 		/* 0x164 */ 
  	RCKEY_DEF_VAL, 		/* 0x165 */ 
  	RCKEY_DEF_VAL, 		/* 0x166 */ 
  	RCKEY_DEF_VAL, 		/* 0x167 */ 
  	RCKEY_DEF_VAL, 		/* 0x168 */ 
  	RCKEY_DEF_VAL, 		/* 0x169 */ 
  	RCKEY_DEF_VAL, 		/* 0x16a */ 
  	RCKEY_DEF_VAL, 		/* 0x16b */ 
  	RCKEY_DEF_VAL, 		/* 0x16c */ 
  	RCKEY_DEF_VAL, 		/* 0x16d */ 
  	RCKEY_DEF_VAL, 		/* 0x16e */ 
  	RCKEY_DEF_VAL, 		/* 0x16f */ 
  	RCKEY_DEF_VAL, 		/* 0x170 */ 
  	RCKEY_DEF_VAL, 		/* 0x171 */ 
  	RCKEY_DEF_VAL, 		/* 0x172 */ 
  	RCKEY_DEF_VAL, 		/* 0x173 */ 
  	RCKEY_DEF_VAL, 		/* 0x174 */ 
  	RCKEY_DEF_VAL, 		/* 0x175 */ 
  	RCKEY_DEF_VAL, 		/* 0x176 */ 
  	RCKEY_DEF_VAL, 		/* 0x177 */ 
  	RCKEY_DEF_VAL, 		/* 0x178 */ 
  	RCKEY_DEF_VAL, 		/* 0x179 */ 
  	RCKEY_DEF_VAL, 		/* 0x17a */ 
  	RCKEY_DEF_VAL, 		/* 0x17b */ 
  	RCKEY_DEF_VAL, 		/* 0x17c */ 
  	RCKEY_DEF_VAL, 		/* 0x17d */ 
  	RCKEY_DEF_VAL, 		/* 0x17e */ 
  	RCKEY_DEF_VAL, 		/* 0x17f */ 
  	RCKEY_DEF_VAL, 		/* 0x180 */ 
  	RCKEY_DEF_VAL, 		/* 0x181 */ 
  	RCKEY_DEF_VAL, 		/* 0x182 */ 
  	RCKEY_DEF_VAL, 		/* 0x183 */ 
  	RCKEY_DEF_VAL, 		/* 0x184 */ 
  	RCKEY_DEF_VAL, 		/* 0x185 */ 
  	RCKEY_DEF_VAL, 		/* 0x186 */ 
  	RCKEY_DEF_VAL, 		/* 0x187 */ 
  	RCKEY_DEF_VAL, 		/* 0x188 */ 
  	RCKEY_DEF_VAL, 		/* 0x189 */ 
  	RCKEY_DEF_VAL, 		/* 0x18a */ 
  	RCKEY_DEF_VAL, 		/* 0x18b */ 
  	RCKEY_DEF_VAL, 		/* 0x18c */ 
  	RCKEY_DEF_VAL, 		/* 0x18d */ 
  	RCKEY_DEF_VAL, 		/* 0x18e */ 
  	RCKEY_DEF_VAL, 		/* 0x18f */ 
  	RCKEY_DEF_VAL, 		/* 0x190 */ 
  	RCKEY_DEF_VAL, 		/* 0x191 */ 
  	RCKEY_DEF_VAL, 		/* 0x192 */ 
  	RCKEY_DEF_VAL, 		/* 0x193 */ 
  	RCKEY_DEF_VAL, 		/* 0x194 */ 
  	RCKEY_DEF_VAL, 		/* 0x195 */ 
  	RCKEY_DEF_VAL, 		/* 0x196 */ 
  	RCKEY_DEF_VAL, 		/* 0x197 */ 
  	RCKEY_DEF_VAL, 		/* 0x198 */ 
  	RCKEY_DEF_VAL, 		/* 0x199 */ 
  	RCKEY_DEF_VAL, 		/* 0x19a */ 
  	RCKEY_DEF_VAL, 		/* 0x19b */ 
  	RCKEY_DEF_VAL, 		/* 0x19c */ 
  	RCKEY_DEF_VAL, 		/* 0x19d */ 
  	RCKEY_DEF_VAL, 		/* 0x19e */ 
  	RCKEY_DEF_VAL, 		/* 0x19f */ 
  	RCKEY_DEF_VAL, 		/* 0x1a0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1a9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1aa */ 
  	RCKEY_DEF_VAL, 		/* 0x1ab */ 
  	RCKEY_DEF_VAL, 		/* 0x1ac */ 
  	RCKEY_DEF_VAL, 		/* 0x1ad */ 
  	RCKEY_DEF_VAL, 		/* 0x1ae */ 
  	RCKEY_DEF_VAL, 		/* 0x1af */ 
  	RCKEY_DEF_VAL, 		/* 0x1b0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1b9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ba */ 
  	RCKEY_DEF_VAL, 		/* 0x1bb */ 
  	RCKEY_DEF_VAL, 		/* 0x1bc */ 
  	RCKEY_DEF_VAL, 		/* 0x1bd */ 
  	RCKEY_DEF_VAL, 		/* 0x1be */ 
  	RCKEY_DEF_VAL, 		/* 0x1bf */ 
  	RCKEY_DEF_VAL, 		/* 0x1c0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1c9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ca */ 
  	RCKEY_DEF_VAL, 		/* 0x1cb */ 
  	RCKEY_DEF_VAL, 		/* 0x1cc */ 
  	RCKEY_DEF_VAL, 		/* 0x1cd */ 
  	RCKEY_DEF_VAL, 		/* 0x1ce */ 
  	RCKEY_DEF_VAL, 		/* 0x1cf */ 
  	RCKEY_DEF_VAL, 		/* 0x1d0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1d9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1da */ 
  	RCKEY_DEF_VAL, 		/* 0x1db */ 
  	RCKEY_DEF_VAL, 		/* 0x1dc */ 
  	RCKEY_DEF_VAL, 		/* 0x1dd */ 
  	RCKEY_DEF_VAL, 		/* 0x1de */ 
  	RCKEY_DEF_VAL, 		/* 0x1df */ 
  	RCKEY_DEF_VAL, 		/* 0x1e0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1e9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1ea */ 
  	RCKEY_DEF_VAL, 		/* 0x1eb */ 
  	RCKEY_DEF_VAL, 		/* 0x1ec */ 
  	RCKEY_DEF_VAL, 		/* 0x1ed */ 
  	RCKEY_DEF_VAL, 		/* 0x1ee */ 
  	RCKEY_DEF_VAL, 		/* 0x1ef */ 
  	RCKEY_DEF_VAL, 		/* 0x1f0 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f1 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f2 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f3 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f4 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f5 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f6 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f7 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f8 */ 
  	RCKEY_DEF_VAL, 		/* 0x1f9 */ 
  	RCKEY_DEF_VAL, 		/* 0x1fa */ 
  	RCKEY_DEF_VAL, 		/* 0x1fb */ 
  	RCKEY_DEF_VAL, 		/* 0x1fc */ 
  	RCKEY_DEF_VAL, 		/* 0x1fd */ 
  	CSAPI_USB_CONNECTION, 	/* 0x1fe */ 
};
#endif
#endif // #ifdef _MERIH_UART1_IAL

#endif /* end of __KEY_CODES_H__ */
