# Configuration for different Architecture such as CSM1200/CSM1201
# Added by xiaodong.fan@celestialsemi.com
# Copyright@celestial
#
 
# define CFLAGS for different chip , it will be automaticly generated by release.sh

CHIP_ARCH = ARCH_CSM1201
