#!/usr/bin/env bash

pushd ../
docker run --rm -it -v $(pwd):/chipbox stulluk/chipbox-docker-builder \
/bin/bash -c "cd /chipbox && \
export APP_WORK=/chipbox \
&& cd Mvapp/ && printf \"\033[1;33m\n****CLEANING****\n\033[0m\" && make clean && printf \"\033[1;33m\n****BUILDING****\n\033[0m\" && sleep 2 && make"
popd
