#!/usr/bin/env bash

pushd ../
docker run -it -v $(pwd):/chipbox stulluk/chipbox-docker-builder \
/bin/bash -c "cd /chipbox && \
export APP_WORK=/chipbox \
&& cd Mvapp/ && make clean && make -j16"
popd
