#ifndef  _CS_APP_ENGNISH_H_
#define  _CS_APP_ENGNISH_H_

#include "mwsetting.h"


static U8* 	EngnishString[CSAPP_STR_MAX]={
"",
"Main Menu",
"Instalação",//"Install",
"Edição de Programa",//"Edit Program",
"Ajuste de Sistema",//"System Setting",
"Informação do Sistema",//"System Info",
"Canal de TV",//"TV Channel",
"Canal de Rádio",//"Radio Channel",
"Canal FAV",//"FAV Channel",
"No channel",
"No program...",
"LCN",
"Nome",//"Name",
"Lock",
"Love",
"Level",
"SNR",
"HD",
"H264",
"AC3",
"CC",
"Progress",
"Modo",
"Frequencia",//"Frequency",
"Banda de",//"Bandwidth",
"MHz",
"Start",
" Manual",
"  Auto",
"  NIT",
"Progress",
"TV number",
"Radio Number",
"Edição de TV ",//"Edit TV",
"Edição Rádio",//"Edit Radio",
"Ajuste AV",//"AV Setting",
"Ajuste do Sistema",//"Sys Setting",
"Ajustes de Tempo",//"Time Setting",
"Ajuste de PIN",//"Pin Setting",
"Definição de Fábrica",//"Factory Def",
"Tipo",//"Type No.",
"Versão do HW",//"HW Version",
"Versão do SW",//"SW Version",
"EPG",
"Channel name",
"No detail information...",
"Program name",
"Book",
"Pre Day",
"Next Day",
"Desc.",
"Mon.",
"Thes.",
"Wed.",
"Thurs.",
"Fri.",
"Sat.",
"Sun.",
"Volume",
"Audio setting",
"Audio lang",
"Audio track",
"Stereo",
"Left",
"Right",
"Mono",
"Frequency:",
"Nível do Sinal",//"Signal Status:",
"No Signal",
"No Service",
"Service Encrypt",
"Teletext language",
"Linguagem da Legenda",//"Subtitle language",
"Razão de Espectro",//"Aspect ratio",
"Aspect mode",
"Definição Vídeo",//"Video def",
"Video output",
"4:3",
"16:9",
"Automático",//"Automatic",
"Letterbox",
" PanScan",
"  Full",
"480p",
"576i",
"576p",
"720p",
"1080i",
"1080p",
"CVBS",
"YC",
"YCbCr",
"YPbPr",
"RGB",
"HDMI",
"Linguagem",//"Menu lang",
"Logic CH Num",
"Parent rate",
"Zona de Tempo",//"Time Zone",
"Modo de Tempo",//"Time Mode",
"Rede",//"Net",
"Local",
"Data",//"Date",
"Hora",//"Time",
"OK: save&exit, MENU/EXIT: cancel&exit",
"Time region",
"Transparência",//"Transparency",
"Appearing order",
"Operator defined",
"Pin Status",
"Habilitado",//"Enable",
"Desabilitado",//"Disable",
"PIN Anterior",//"Old pin",
"Novo PIN",//"New pin",
"Confirme PIN",//"Confirm pin",
"PIN de entrada",//"Input PIN",
"Password",
"Old password Error.",
"Confirm password Error",
"New Password success",
"Warning",
"This will clear all services, \ncontinue?",
"Data is changed, save?",
"OK",
"CANCEL",
"Press OK to comfirm, Press EXIT \nto cancel",
"Remove",//"Delete",
"Trava",//"Lock",
"Favorito",//"Fav",
"Ordena",//"Sort",
"Voce tem certeza de apagar \ntodos os serviços e ajustes \ndo usuário ?",//"Are you sure to clear all \nservices and reset user \nsettings?",
"Loading default settings, please don't shut power!",
"SPDIF",
"PCM",
"AC3"

};


#endif
/*   E O F  */


