#ifndef CYGONCE_PKGCONF_HAL_ARM_ARM9_ORION_H
#define CYGONCE_PKGCONF_HAL_ARM_ARM9_ORION_H
/*
 * File <pkgconf/hal_arm_arm9_orion.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "ARM9"
#define HAL_PLATFORM_BOARD  "Orion system"
#define HAL_PLATFORM_EXTRA  ""
#define HAL_ARCH_PROGRAM_NEW_STACK orion_program_new_stack
#define HAL_PLATFORM_MACHINE_TYPE  719
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 1000
#define CYGNUM_HAL_RTC_DENOMINATOR_1000
#define CYGNUM_HAL_RTC_PERIOD 55000
#define CYGNUM_HAL_RTC_PERIOD_55000
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
