#!/usr/bin/env bash

pushd ../
docker run -it -v $(pwd):/chipbox stulluk/chipbox-docker-builder \
/bin/bash -c "cd /chipbox && \
cd oscam/ && mkdir -p build \
&& cd build \
&& cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/toolchain-arm-dockstar-openwrt.cmake .. \
&& make -j16"
popd
